// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseAlarm = KRPC.Client.Services.SpaceCenter.Alarm;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Alarm object.
/// </summary>
public class Alarm
{
    internal BaseAlarm Internal { get; }

    internal Alarm(BaseAlarm alarm)
    {
        ArgumentNullException.ThrowIfNull(alarm);
        Internal = alarm;
    }

    /// <inheritdoc />
    public string Description
        => Internal.Description;

    /// <inheritdoc />
    public double EventOffset
        => Internal.EventOffset;

    /// <inheritdoc />
    public uint ID
        => Internal.ID;

    /// <inheritdoc />
    public double Time
        => Internal.Time;

    /// <inheritdoc />
    public double TimeUntil
        => Internal.TimeUntil;

    /// <inheritdoc />
    public string Title
        => Internal.Title;

    /// <inheritdoc />
    public string Type
        => Internal.Type;

    /// <inheritdoc />
    public Vessel Vessel
        => new Vessel(Internal.Vessel);
}
