// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseAntenna = KRPC.Client.Services.SpaceCenter.Antenna;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Antenna object.
/// </summary>
public class Antenna
{
    internal BaseAntenna Internal { get; }

    internal Antenna(BaseAntenna antenna)
    {
        ArgumentNullException.ThrowIfNull(antenna);
        Internal = antenna;
    }

    /// <inheritdoc />
    public bool AllowPartial
    {
        get => Internal.AllowPartial;
        set => Internal.AllowPartial = value;
    }

    /// <inheritdoc />
    public bool CanTransmit
        => Internal.CanTransmit;

    /// <inheritdoc />
    public bool Combinable
        => Internal.Combinable;

    /// <inheritdoc />
    public double CombinableExponent
        => Internal.CombinableExponent;

    /// <inheritdoc />
    public bool Deployable
        => Internal.Deployable;

    /// <inheritdoc />
    public bool Deployed
    {
        get => Internal.Deployed;
        set => Internal.Deployed = value;
    }

    /// <inheritdoc />
    public float PacketInterval
        => Internal.PacketInterval;

    /// <inheritdoc />
    public double PacketResourceCost
        => Internal.PacketResourceCost;

    /// <inheritdoc />
    public float PacketSize
        => Internal.PacketSize;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public double Power
        => Internal.Power;

    /// <inheritdoc />
    public AntennaState State
        => Internal.State;

    /// <inheritdoc />
    public void Cancel()
        => Internal.Cancel();

    /// <inheritdoc />
    public void Transmit()
        => Internal.Transmit();
}
