// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseAutoPilot = KRPC.Client.Services.SpaceCenter.AutoPilot;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter AutoPilot object.
/// </summary>
public class AutoPilot
{
    internal BaseAutoPilot Internal { get; }

    internal AutoPilot(BaseAutoPilot autoPilot)
    {
        ArgumentNullException.ThrowIfNull(autoPilot);
        Internal = autoPilot;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> AttenuationAngle
    {
        get => Internal.AttenuationAngle;
        set => Internal.AttenuationAngle = value;
    }

    /// <inheritdoc />
    public bool AutoTune
    {
        get => Internal.AutoTune;
        set => Internal.AutoTune = value;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> DecelerationTime
    {
        get => Internal.DecelerationTime;
        set => Internal.DecelerationTime = value;
    }

    /// <inheritdoc />
    public float Error
        => Internal.Error;

    /// <inheritdoc />
    public float HeadingError
        => Internal.HeadingError;

    /// <inheritdoc />
    public Tuple<double, double, double> Overshoot
    {
        get => Internal.Overshoot;
        set => Internal.Overshoot = value;
    }

    /// <inheritdoc />
    public float PitchError
        => Internal.PitchError;

    /// <inheritdoc />
    public Tuple<double, double, double> PitchPIDGains
    {
        get => Internal.PitchPIDGains;
        set => Internal.PitchPIDGains = value;
    }

    /// <inheritdoc />
    public ReferenceFrame ReferenceFrame
    {
        get => new ReferenceFrame(Internal.ReferenceFrame);
        set => Internal.ReferenceFrame = value.Internal;
    }

    /// <inheritdoc />
    public float RollError
        => Internal.RollError;

    /// <inheritdoc />
    public Tuple<double, double, double> RollPIDGains
    {
        get => Internal.RollPIDGains;
        set => Internal.RollPIDGains = value;
    }

    /// <inheritdoc />
    public double RollThreshold
    {
        get => Internal.RollThreshold;
        set => Internal.RollThreshold = value;
    }

    /// <inheritdoc />
    public bool SAS
    {
        get => Internal.SAS;
        set => Internal.SAS = value;
    }

    /// <inheritdoc />
    public SASMode SASMode
    {
        get => Internal.SASMode;
        set => Internal.SASMode = value;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> StoppingTime
    {
        get => Internal.StoppingTime;
        set => Internal.StoppingTime = value;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> TargetDirection
    {
        get => Internal.TargetDirection;
        set => Internal.TargetDirection = value;
    }

    /// <inheritdoc />
    public float TargetHeading
    {
        get => Internal.TargetHeading;
        set => Internal.TargetHeading = value;
    }

    /// <inheritdoc />
    public float TargetPitch
    {
        get => Internal.TargetPitch;
        set => Internal.TargetPitch = value;
    }

    /// <inheritdoc />
    public float TargetRoll
    {
        get => Internal.TargetRoll;
        set => Internal.TargetRoll = value;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> TimeToPeak
    {
        get => Internal.TimeToPeak;
        set => Internal.TimeToPeak = value;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> YawPIDGains
    {
        get => Internal.YawPIDGains;
        set => Internal.YawPIDGains = value;
    }

    /// <inheritdoc />
    public void Disengage()
        => Internal.Disengage();

    /// <inheritdoc />
    public void Engage()
        => Internal.Engage();

    /// <inheritdoc />
    public void TargetPitchAndHeading(float pitch, float heading)
        => Internal.TargetPitchAndHeading(pitch, heading);

    /// <inheritdoc />
    public void Wait()
        => Internal.Wait();
}
