// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseCamera = KRPC.Client.Services.SpaceCenter.Camera;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Camera object.
/// </summary>
public class Camera
{
    internal BaseCamera Internal { get; }

    internal Camera(BaseCamera camera)
    {
        ArgumentNullException.ThrowIfNull(camera);
        Internal = camera;
    }

    /// <inheritdoc />
    public float DefaultDistance
        => Internal.DefaultDistance;

    /// <inheritdoc />
    public float Distance
    {
        get => Internal.Distance;
        set => Internal.Distance = value;
    }

    /// <inheritdoc />
    public CelestialBody FocussedBody
    {
        get => new CelestialBody(Internal.FocussedBody);
        set => Internal.FocussedBody = value.Internal;
    }

    /// <inheritdoc />
    public Node FocussedNode
    {
        get => new Node(Internal.FocussedNode);
        set => Internal.FocussedNode = value.Internal;
    }

    /// <inheritdoc />
    public Vessel FocussedVessel
    {
        get => new Vessel(Internal.FocussedVessel);
        set => Internal.FocussedVessel = value.Internal;
    }

    /// <inheritdoc />
    public float Heading
    {
        get => Internal.Heading;
        set => Internal.Heading = value;
    }

    /// <inheritdoc />
    public float MaxDistance
        => Internal.MaxDistance;

    /// <inheritdoc />
    public float MaxPitch
        => Internal.MaxPitch;

    /// <inheritdoc />
    public float MinDistance
        => Internal.MinDistance;

    /// <inheritdoc />
    public float MinPitch
        => Internal.MinPitch;

    /// <inheritdoc />
    public CameraMode Mode
    {
        get => Internal.Mode;
        set => Internal.Mode = value;
    }

    /// <inheritdoc />
    public float Pitch
    {
        get => Internal.Pitch;
        set => Internal.Pitch = value;
    }
}
