// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseCargoBay = KRPC.Client.Services.SpaceCenter.CargoBay;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter CargoBay object.
/// </summary>
public class CargoBay
{
    internal BaseCargoBay Internal { get; }

    internal CargoBay(BaseCargoBay cargoBay)
    {
        ArgumentNullException.ThrowIfNull(cargoBay);
        Internal = cargoBay;
    }

    /// <inheritdoc />
    public bool Open
    {
        get => Internal.Open;
        set => Internal.Open = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public CargoBayState State
        => Internal.State;
}
