// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseCelestialBody = KRPC.Client.Services.SpaceCenter.CelestialBody;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter CelestialBody object.
/// </summary>
public class CelestialBody
{
    internal BaseCelestialBody Internal { get; }

    internal CelestialBody(BaseCelestialBody celestialBody)
    {
        ArgumentNullException.ThrowIfNull(celestialBody);
        Internal = celestialBody;
    }

    /// <inheritdoc />
    public double AtmosphereDepth
        => Internal.AtmosphereDepth;

    /// <inheritdoc />
    public ISet<string> Biomes
        => Internal.Biomes;

    /// <inheritdoc />
    public double EquatorialRadius
        => Internal.EquatorialRadius;

    /// <inheritdoc />
    public float FlyingHighAltitudeThreshold
        => Internal.FlyingHighAltitudeThreshold;

    /// <inheritdoc />
    public double GravitationalParameter
        => Internal.GravitationalParameter;

    /// <inheritdoc />
    public bool HasAtmosphere
        => Internal.HasAtmosphere;

    /// <inheritdoc />
    public bool HasAtmosphericOxygen
        => Internal.HasAtmosphericOxygen;

    /// <inheritdoc />
    public bool HasSolidSurface
        => Internal.HasSolidSurface;

    /// <inheritdoc />
    public double InitialRotation
        => Internal.InitialRotation;

    /// <inheritdoc />
    public bool IsStar
        => Internal.IsStar;

    /// <inheritdoc />
    public double Mass
        => Internal.Mass;

    /// <inheritdoc />
    public string Name
        => Internal.Name;

    /// <inheritdoc />
    public ReferenceFrame NonRotatingReferenceFrame
        => new ReferenceFrame(Internal.NonRotatingReferenceFrame);

    /// <inheritdoc />
    public Orbit Orbit
        => new Orbit(Internal.Orbit);

    /// <inheritdoc />
    public ReferenceFrame OrbitalReferenceFrame
        => new ReferenceFrame(Internal.OrbitalReferenceFrame);

    /// <inheritdoc />
    public ReferenceFrame ReferenceFrame
        => new ReferenceFrame(Internal.ReferenceFrame);

    /// <inheritdoc />
    public double RotationAngle
        => Internal.RotationAngle;

    /// <inheritdoc />
    public double RotationalPeriod
        => Internal.RotationalPeriod;

    /// <inheritdoc />
    public double RotationalSpeed
        => Internal.RotationalSpeed;

    /// <inheritdoc />
    public IList<CelestialBody> Satellites
        => Internal.Satellites.Select(item => new CelestialBody(item)).ToList();

    /// <inheritdoc />
    public float SpaceHighAltitudeThreshold
        => Internal.SpaceHighAltitudeThreshold;

    /// <inheritdoc />
    public double SphereOfInfluence
        => Internal.SphereOfInfluence;

    /// <inheritdoc />
    public double SurfaceGravity
        => Internal.SurfaceGravity;

    /// <inheritdoc />
    public double AltitudeAtPosition(Tuple<double, double, double> position, ReferenceFrame referenceFrame)
        => Internal.AltitudeAtPosition(position, referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> AngularVelocity(ReferenceFrame referenceFrame)
        => Internal.AngularVelocity(referenceFrame.Internal);

    /// <inheritdoc />
    public double AtmosphericDensityAtPosition(Tuple<double, double, double> position, ReferenceFrame referenceFrame)
        => Internal.AtmosphericDensityAtPosition(position, referenceFrame.Internal);

    /// <inheritdoc />
    public double BedrockHeight(double latitude, double longitude)
        => Internal.BedrockHeight(latitude, longitude);

    /// <inheritdoc />
    public Tuple<double, double, double> BedrockPosition(double latitude, double longitude, ReferenceFrame referenceFrame)
        => Internal.BedrockPosition(latitude, longitude, referenceFrame.Internal);

    /// <inheritdoc />
    public string BiomeAt(double latitude, double longitude)
        => Internal.BiomeAt(latitude, longitude);

    /// <inheritdoc />
    public double DensityAt(double altitude)
        => Internal.DensityAt(altitude);

    /// <inheritdoc />
    public Tuple<double, double, double> Direction(ReferenceFrame referenceFrame)
        => Internal.Direction(referenceFrame.Internal);

    /// <inheritdoc />
    public double LatitudeAtPosition(Tuple<double, double, double> position, ReferenceFrame referenceFrame)
        => Internal.LatitudeAtPosition(position, referenceFrame.Internal);

    /// <inheritdoc />
    public double LongitudeAtPosition(Tuple<double, double, double> position, ReferenceFrame referenceFrame)
        => Internal.LongitudeAtPosition(position, referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> MSLPosition(double latitude, double longitude, ReferenceFrame referenceFrame)
        => Internal.MSLPosition(latitude, longitude, referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Position(ReferenceFrame referenceFrame)
        => Internal.Position(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> PositionAtAltitude(double latitude, double longitude, double altitude, ReferenceFrame referenceFrame)
        => Internal.PositionAtAltitude(latitude, longitude, altitude, referenceFrame.Internal);

    /// <inheritdoc />
    public double PressureAt(double altitude)
        => Internal.PressureAt(altitude);

    /// <inheritdoc />
    public Tuple<double, double, double, double> Rotation(ReferenceFrame referenceFrame)
        => Internal.Rotation(referenceFrame.Internal);

    /// <inheritdoc />
    public double SurfaceHeight(double latitude, double longitude)
        => Internal.SurfaceHeight(latitude, longitude);

    /// <inheritdoc />
    public Tuple<double, double, double> SurfacePosition(double latitude, double longitude, ReferenceFrame referenceFrame)
        => Internal.SurfacePosition(latitude, longitude, referenceFrame.Internal);

    /// <inheritdoc />
    public double TemperatureAt(Tuple<double, double, double> position, ReferenceFrame referenceFrame)
        => Internal.TemperatureAt(position, referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Velocity(ReferenceFrame referenceFrame)
        => Internal.Velocity(referenceFrame.Internal);
}
