// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseCommLink = KRPC.Client.Services.SpaceCenter.CommLink;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter CommLink object.
/// </summary>
public class CommLink
{
    internal BaseCommLink Internal { get; }

    internal CommLink(BaseCommLink commLink)
    {
        ArgumentNullException.ThrowIfNull(commLink);
        Internal = commLink;
    }

    /// <inheritdoc />
    public CommNode End
        => new CommNode(Internal.End);

    /// <inheritdoc />
    public double SignalStrength
        => Internal.SignalStrength;

    /// <inheritdoc />
    public CommNode Start
        => new CommNode(Internal.Start);

    /// <inheritdoc />
    public CommLinkType Type
        => Internal.Type;
}
