// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseCommNode = KRPC.Client.Services.SpaceCenter.CommNode;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter CommNode object.
/// </summary>
public class CommNode
{
    internal BaseCommNode Internal { get; }

    internal CommNode(BaseCommNode commNode)
    {
        ArgumentNullException.ThrowIfNull(commNode);
        Internal = commNode;
    }

    /// <inheritdoc />
    public bool IsControlPoint
        => Internal.IsControlPoint;

    /// <inheritdoc />
    public bool IsHome
        => Internal.IsHome;

    /// <inheritdoc />
    public bool IsVessel
        => Internal.IsVessel;

    /// <inheritdoc />
    public string Name
        => Internal.Name;

    /// <inheritdoc />
    public Vessel Vessel
        => new Vessel(Internal.Vessel);
}
