// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseComms = KRPC.Client.Services.SpaceCenter.Comms;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Comms object.
/// </summary>
public class Comms
{
    internal BaseComms Internal { get; }

    internal Comms(BaseComms comms)
    {
        ArgumentNullException.ThrowIfNull(comms);
        Internal = comms;
    }

    /// <inheritdoc />
    public bool CanCommunicate
        => Internal.CanCommunicate;

    /// <inheritdoc />
    public bool CanTransmitScience
        => Internal.CanTransmitScience;

    /// <inheritdoc />
    public IList<CommLink> ControlPath
        => Internal.ControlPath.Select(item => new CommLink(item)).ToList();

    /// <inheritdoc />
    public double Power
        => Internal.Power;

    /// <inheritdoc />
    public double SignalDelay
        => Internal.SignalDelay;

    /// <inheritdoc />
    public double SignalStrength
        => Internal.SignalStrength;
}
