// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseControl = KRPC.Client.Services.SpaceCenter.Control;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Control object.
/// </summary>
public class Control
{
    internal BaseControl Internal { get; }

    internal Control(BaseControl control)
    {
        ArgumentNullException.ThrowIfNull(control);
        Internal = control;
    }

    /// <inheritdoc />
    public bool Abort
    {
        get => Internal.Abort;
        set => Internal.Abort = value;
    }

    /// <inheritdoc />
    public bool Antennas
    {
        get => Internal.Antennas;
        set => Internal.Antennas = value;
    }

    /// <inheritdoc />
    public bool Brakes
    {
        get => Internal.Brakes;
        set => Internal.Brakes = value;
    }

    /// <inheritdoc />
    public bool CargoBays
    {
        get => Internal.CargoBays;
        set => Internal.CargoBays = value;
    }

    /// <inheritdoc />
    public int CurrentStage
        => Internal.CurrentStage;

    /// <inheritdoc />
    public float CustomAxis01
    {
        get => Internal.CustomAxis01;
        set => Internal.CustomAxis01 = value;
    }

    /// <inheritdoc />
    public float CustomAxis02
    {
        get => Internal.CustomAxis02;
        set => Internal.CustomAxis02 = value;
    }

    /// <inheritdoc />
    public float CustomAxis03
    {
        get => Internal.CustomAxis03;
        set => Internal.CustomAxis03 = value;
    }

    /// <inheritdoc />
    public float CustomAxis04
    {
        get => Internal.CustomAxis04;
        set => Internal.CustomAxis04 = value;
    }

    /// <inheritdoc />
    public float Forward
    {
        get => Internal.Forward;
        set => Internal.Forward = value;
    }

    /// <inheritdoc />
    public bool Gear
    {
        get => Internal.Gear;
        set => Internal.Gear = value;
    }

    /// <inheritdoc />
    public ControlInputMode InputMode
    {
        get => Internal.InputMode;
        set => Internal.InputMode = value;
    }

    /// <inheritdoc />
    public bool Intakes
    {
        get => Internal.Intakes;
        set => Internal.Intakes = value;
    }

    /// <inheritdoc />
    public bool Legs
    {
        get => Internal.Legs;
        set => Internal.Legs = value;
    }

    /// <inheritdoc />
    public bool Lights
    {
        get => Internal.Lights;
        set => Internal.Lights = value;
    }

    /// <inheritdoc />
    public IList<Node> Nodes
        => Internal.Nodes.Select(item => new Node(item)).ToList();

    /// <inheritdoc />
    public bool Parachutes
    {
        get => Internal.Parachutes;
        set => Internal.Parachutes = value;
    }

    /// <inheritdoc />
    public float Pitch
    {
        get => Internal.Pitch;
        set => Internal.Pitch = value;
    }

    /// <inheritdoc />
    public bool RCS
    {
        get => Internal.RCS;
        set => Internal.RCS = value;
    }

    /// <inheritdoc />
    public bool Radiators
    {
        get => Internal.Radiators;
        set => Internal.Radiators = value;
    }

    /// <inheritdoc />
    public bool ReactionWheels
    {
        get => Internal.ReactionWheels;
        set => Internal.ReactionWheels = value;
    }

    /// <inheritdoc />
    public bool ResourceHarvesters
    {
        get => Internal.ResourceHarvesters;
        set => Internal.ResourceHarvesters = value;
    }

    /// <inheritdoc />
    public bool ResourceHarvestersActive
    {
        get => Internal.ResourceHarvestersActive;
        set => Internal.ResourceHarvestersActive = value;
    }

    /// <inheritdoc />
    public float Right
    {
        get => Internal.Right;
        set => Internal.Right = value;
    }

    /// <inheritdoc />
    public float Roll
    {
        get => Internal.Roll;
        set => Internal.Roll = value;
    }

    /// <inheritdoc />
    public bool SAS
    {
        get => Internal.SAS;
        set => Internal.SAS = value;
    }

    /// <inheritdoc />
    public SASMode SASMode
    {
        get => Internal.SASMode;
        set => Internal.SASMode = value;
    }

    /// <inheritdoc />
    public bool SolarPanels
    {
        get => Internal.SolarPanels;
        set => Internal.SolarPanels = value;
    }

    /// <inheritdoc />
    public ControlSource Source
        => Internal.Source;

    /// <inheritdoc />
    public SpeedMode SpeedMode
    {
        get => Internal.SpeedMode;
        set => Internal.SpeedMode = value;
    }

    /// <inheritdoc />
    public bool StageLock
    {
        get => Internal.StageLock;
        set => Internal.StageLock = value;
    }

    /// <inheritdoc />
    public ControlState State
        => Internal.State;

    /// <inheritdoc />
    public float Throttle
    {
        get => Internal.Throttle;
        set => Internal.Throttle = value;
    }

    /// <inheritdoc />
    public float Up
    {
        get => Internal.Up;
        set => Internal.Up = value;
    }

    /// <inheritdoc />
    public float WheelSteering
    {
        get => Internal.WheelSteering;
        set => Internal.WheelSteering = value;
    }

    /// <inheritdoc />
    public float WheelThrottle
    {
        get => Internal.WheelThrottle;
        set => Internal.WheelThrottle = value;
    }

    /// <inheritdoc />
    public bool Wheels
    {
        get => Internal.Wheels;
        set => Internal.Wheels = value;
    }

    /// <inheritdoc />
    public float Yaw
    {
        get => Internal.Yaw;
        set => Internal.Yaw = value;
    }

    /// <inheritdoc />
    public IList<Vessel> ActivateNextStage()
        => Internal.ActivateNextStage().Select(item => new Vessel(item)).ToList();

    /// <inheritdoc />
    public Node AddNode(double ut, float prograde = 0f, float normal = 0f, float radial = 0f)
        => new Node(Internal.AddNode(ut, prograde, normal, radial));

    /// <inheritdoc />
    public bool GetActionGroup(uint group)
        => Internal.GetActionGroup(group);

    /// <inheritdoc />
    public void RemoveNodes()
        => Internal.RemoveNodes();

    /// <inheritdoc />
    public void SetActionGroup(uint group, bool state)
        => Internal.SetActionGroup(group, state);

    /// <inheritdoc />
    public void ToggleActionGroup(uint group)
        => Internal.ToggleActionGroup(group);
}
