// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseContract = KRPC.Client.Services.SpaceCenter.Contract;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Contract object.
/// </summary>
public class Contract
{
    internal BaseContract Internal { get; }

    internal Contract(BaseContract contract)
    {
        ArgumentNullException.ThrowIfNull(contract);
        Internal = contract;
    }

    /// <inheritdoc />
    public bool Active
        => Internal.Active;

    /// <inheritdoc />
    public bool CanBeCanceled
        => Internal.CanBeCanceled;

    /// <inheritdoc />
    public bool CanBeDeclined
        => Internal.CanBeDeclined;

    /// <inheritdoc />
    public bool CanBeFailed
        => Internal.CanBeFailed;

    /// <inheritdoc />
    public string Description
        => Internal.Description;

    /// <inheritdoc />
    public bool Failed
        => Internal.Failed;

    /// <inheritdoc />
    public double FundsAdvance
        => Internal.FundsAdvance;

    /// <inheritdoc />
    public double FundsCompletion
        => Internal.FundsCompletion;

    /// <inheritdoc />
    public double FundsFailure
        => Internal.FundsFailure;

    /// <inheritdoc />
    public IList<string> Keywords
        => Internal.Keywords;

    /// <inheritdoc />
    public string Notes
        => Internal.Notes;

    /// <inheritdoc />
    public IList<ContractParameter> Parameters
        => Internal.Parameters.Select(item => new ContractParameter(item)).ToList();

    /// <inheritdoc />
    public bool Read
        => Internal.Read;

    /// <inheritdoc />
    public double ReputationCompletion
        => Internal.ReputationCompletion;

    /// <inheritdoc />
    public double ReputationFailure
        => Internal.ReputationFailure;

    /// <inheritdoc />
    public double ScienceCompletion
        => Internal.ScienceCompletion;

    /// <inheritdoc />
    public bool Seen
        => Internal.Seen;

    /// <inheritdoc />
    public ContractState State
        => Internal.State;

    /// <inheritdoc />
    public string Synopsis
        => Internal.Synopsis;

    /// <inheritdoc />
    public string Title
        => Internal.Title;

    /// <inheritdoc />
    public string Type
        => Internal.Type;

    /// <inheritdoc />
    public void Accept()
        => Internal.Accept();

    /// <inheritdoc />
    public void Cancel()
        => Internal.Cancel();

    /// <inheritdoc />
    public void Decline()
        => Internal.Decline();
}
