// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseContractParameter = KRPC.Client.Services.SpaceCenter.ContractParameter;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ContractParameter object.
/// </summary>
public class ContractParameter
{
    internal BaseContractParameter Internal { get; }

    internal ContractParameter(BaseContractParameter contractParameter)
    {
        ArgumentNullException.ThrowIfNull(contractParameter);
        Internal = contractParameter;
    }

    /// <inheritdoc />
    public IList<ContractParameter> Children
        => Internal.Children.Select(item => new ContractParameter(item)).ToList();

    /// <inheritdoc />
    public bool Completed
        => Internal.Completed;

    /// <inheritdoc />
    public bool Failed
        => Internal.Failed;

    /// <inheritdoc />
    public double FundsCompletion
        => Internal.FundsCompletion;

    /// <inheritdoc />
    public double FundsFailure
        => Internal.FundsFailure;

    /// <inheritdoc />
    public string Notes
        => Internal.Notes;

    /// <inheritdoc />
    public bool Optional
        => Internal.Optional;

    /// <inheritdoc />
    public double ReputationCompletion
        => Internal.ReputationCompletion;

    /// <inheritdoc />
    public double ReputationFailure
        => Internal.ReputationFailure;

    /// <inheritdoc />
    public double ScienceCompletion
        => Internal.ScienceCompletion;

    /// <inheritdoc />
    public string Title
        => Internal.Title;
}
