// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseControlSurface = KRPC.Client.Services.SpaceCenter.ControlSurface;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ControlSurface object.
/// </summary>
public class ControlSurface
{
    internal BaseControlSurface Internal { get; }

    internal ControlSurface(BaseControlSurface controlSurface)
    {
        ArgumentNullException.ThrowIfNull(controlSurface);
        Internal = controlSurface;
    }

    /// <inheritdoc />
    public float AuthorityLimiter
    {
        get => Internal.AuthorityLimiter;
        set => Internal.AuthorityLimiter = value;
    }

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableTorque
        => Internal.AvailableTorque;

    /// <inheritdoc />
    public bool Deployed
    {
        get => Internal.Deployed;
        set => Internal.Deployed = value;
    }

    /// <inheritdoc />
    public bool Inverted
    {
        get => Internal.Inverted;
        set => Internal.Inverted = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public bool PitchEnabled
    {
        get => Internal.PitchEnabled;
        set => Internal.PitchEnabled = value;
    }

    /// <inheritdoc />
    public bool RollEnabled
    {
        get => Internal.RollEnabled;
        set => Internal.RollEnabled = value;
    }

    /// <inheritdoc />
    public float SurfaceArea
        => Internal.SurfaceArea;

    /// <inheritdoc />
    public bool YawEnabled
    {
        get => Internal.YawEnabled;
        set => Internal.YawEnabled = value;
    }
}
