// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseCrewMember = KRPC.Client.Services.SpaceCenter.CrewMember;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter CrewMember object.
/// </summary>
public class CrewMember
{
    internal BaseCrewMember Internal { get; }

    internal CrewMember(BaseCrewMember crewMember)
    {
        ArgumentNullException.ThrowIfNull(crewMember);
        Internal = crewMember;
    }

    /// <inheritdoc />
    public bool Badass
    {
        get => Internal.Badass;
        set => Internal.Badass = value;
    }

    /// <inheritdoc />
    public IList<int> CareerLogFlights
        => Internal.CareerLogFlights;

    /// <inheritdoc />
    public IList<string> CareerLogTargets
        => Internal.CareerLogTargets;

    /// <inheritdoc />
    public IList<string> CareerLogTypes
        => Internal.CareerLogTypes;

    /// <inheritdoc />
    public float Courage
    {
        get => Internal.Courage;
        set => Internal.Courage = value;
    }

    /// <inheritdoc />
    public float Experience
    {
        get => Internal.Experience;
        set => Internal.Experience = value;
    }

    /// <inheritdoc />
    public CrewMemberGender Gender
        => Internal.Gender;

    /// <inheritdoc />
    public string Name
    {
        get => Internal.Name;
        set => Internal.Name = value;
    }

    /// <inheritdoc />
    public bool OnMission
        => Internal.OnMission;

    /// <inheritdoc />
    public RosterStatus RosterStatus
        => Internal.RosterStatus;

    /// <inheritdoc />
    public float Stupidity
    {
        get => Internal.Stupidity;
        set => Internal.Stupidity = value;
    }

    /// <inheritdoc />
    public SuitType SuitType
    {
        get => Internal.SuitType;
        set => Internal.SuitType = value;
    }

    /// <inheritdoc />
    public string Trait
        => Internal.Trait;

    /// <inheritdoc />
    public CrewMemberType Type
        => Internal.Type;

    /// <inheritdoc />
    public bool Veteran
    {
        get => Internal.Veteran;
        set => Internal.Veteran = value;
    }
}
