// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseDecoupler = KRPC.Client.Services.SpaceCenter.Decoupler;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Decoupler object.
/// </summary>
public class Decoupler
{
    internal BaseDecoupler Internal { get; }

    internal Decoupler(BaseDecoupler decoupler)
    {
        ArgumentNullException.ThrowIfNull(decoupler);
        Internal = decoupler;
    }

    /// <inheritdoc />
    public Part AttachedPart
        => new Part(Internal.AttachedPart);

    /// <inheritdoc />
    public bool Decoupled
        => Internal.Decoupled;

    /// <inheritdoc />
    public float Impulse
        => Internal.Impulse;

    /// <inheritdoc />
    public bool IsOmniDecoupler
        => Internal.IsOmniDecoupler;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public bool Staged
        => Internal.Staged;

    /// <inheritdoc />
    public Vessel Decouple()
        => new Vessel(Internal.Decouple());
}
