// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseDockingPort = KRPC.Client.Services.SpaceCenter.DockingPort;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter DockingPort object.
/// </summary>
public class DockingPort
{
    internal BaseDockingPort Internal { get; }

    internal DockingPort(BaseDockingPort dockingPort)
    {
        ArgumentNullException.ThrowIfNull(dockingPort);
        Internal = dockingPort;
    }

    /// <inheritdoc />
    public bool CanRotate
        => Internal.CanRotate;

    /// <inheritdoc />
    public Part DockedPart
        => new Part(Internal.DockedPart);

    /// <inheritdoc />
    public bool HasShield
        => Internal.HasShield;

    /// <inheritdoc />
    public float MaximumRotation
        => Internal.MaximumRotation;

    /// <inheritdoc />
    public float MinimumRotation
        => Internal.MinimumRotation;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float ReengageDistance
        => Internal.ReengageDistance;

    /// <inheritdoc />
    public ReferenceFrame ReferenceFrame
        => new ReferenceFrame(Internal.ReferenceFrame);

    /// <inheritdoc />
    public bool RotationLocked
    {
        get => Internal.RotationLocked;
        set => Internal.RotationLocked = value;
    }

    /// <inheritdoc />
    public float RotationTarget
    {
        get => Internal.RotationTarget;
        set => Internal.RotationTarget = value;
    }

    /// <inheritdoc />
    public bool Shielded
    {
        get => Internal.Shielded;
        set => Internal.Shielded = value;
    }

    /// <inheritdoc />
    public DockingPortState State
        => Internal.State;

    /// <inheritdoc />
    public Tuple<double, double, double> Direction(ReferenceFrame referenceFrame)
        => Internal.Direction(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Position(ReferenceFrame referenceFrame)
        => Internal.Position(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double, double> Rotation(ReferenceFrame referenceFrame)
        => Internal.Rotation(referenceFrame.Internal);

    /// <inheritdoc />
    public Vessel Undock()
        => new Vessel(Internal.Undock());
}
