// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseEngine = KRPC.Client.Services.SpaceCenter.Engine;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Engine object.
/// </summary>
public class Engine
{
    internal BaseEngine Internal { get; }

    internal Engine(BaseEngine engine)
    {
        ArgumentNullException.ThrowIfNull(engine);
        Internal = engine;
    }

    /// <inheritdoc />
    public bool Active
    {
        get => Internal.Active;
        set => Internal.Active = value;
    }

    /// <inheritdoc />
    public bool AutoModeSwitch
    {
        get => Internal.AutoModeSwitch;
        set => Internal.AutoModeSwitch = value;
    }

    /// <inheritdoc />
    public float AvailableThrust
        => Internal.AvailableThrust;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableTorque
        => Internal.AvailableTorque;

    /// <inheritdoc />
    public bool CanRestart
        => Internal.CanRestart;

    /// <inheritdoc />
    public bool CanShutdown
        => Internal.CanShutdown;

    /// <inheritdoc />
    public float GimbalLimit
    {
        get => Internal.GimbalLimit;
        set => Internal.GimbalLimit = value;
    }

    /// <inheritdoc />
    public bool GimbalLocked
    {
        get => Internal.GimbalLocked;
        set => Internal.GimbalLocked = value;
    }

    /// <inheritdoc />
    public float GimbalRange
        => Internal.GimbalRange;

    /// <inheritdoc />
    public bool Gimballed
        => Internal.Gimballed;

    /// <inheritdoc />
    public bool HasFuel
        => Internal.HasFuel;

    /// <inheritdoc />
    public bool HasModes
        => Internal.HasModes;

    /// <inheritdoc />
    public bool IndependentThrottle
    {
        get => Internal.IndependentThrottle;
        set => Internal.IndependentThrottle = value;
    }

    /// <inheritdoc />
    public float KerbinSeaLevelSpecificImpulse
        => Internal.KerbinSeaLevelSpecificImpulse;

    /// <inheritdoc />
    public float MaxThrust
        => Internal.MaxThrust;

    /// <inheritdoc />
    public float MaxVacuumThrust
        => Internal.MaxVacuumThrust;

    /// <inheritdoc />
    public string Mode
    {
        get => Internal.Mode;
        set => Internal.Mode = value;
    }

    /// <inheritdoc />
    public IDictionary<string, Engine> Modes
        => Internal.Modes.ToDictionary(pair => pair.Key, pair => new Engine(pair.Value));

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public IList<string> PropellantNames
        => Internal.PropellantNames;

    /// <inheritdoc />
    public IDictionary<string, float> PropellantRatios
        => Internal.PropellantRatios;

    /// <inheritdoc />
    public IList<Propellant> Propellants
        => Internal.Propellants.Select(item => new Propellant(item)).ToList();

    /// <inheritdoc />
    public float SpecificImpulse
        => Internal.SpecificImpulse;

    /// <inheritdoc />
    public float Throttle
    {
        get => Internal.Throttle;
        set => Internal.Throttle = value;
    }

    /// <inheritdoc />
    public bool ThrottleLocked
        => Internal.ThrottleLocked;

    /// <inheritdoc />
    public float Thrust
        => Internal.Thrust;

    /// <inheritdoc />
    public float ThrustLimit
    {
        get => Internal.ThrustLimit;
        set => Internal.ThrustLimit = value;
    }

    /// <inheritdoc />
    public IList<Thruster> Thrusters
        => Internal.Thrusters.Select(item => new Thruster(item)).ToList();

    /// <inheritdoc />
    public float VacuumSpecificImpulse
        => Internal.VacuumSpecificImpulse;

    /// <inheritdoc />
    public float AvailableThrustAt(double pressure)
        => Internal.AvailableThrustAt(pressure);

    /// <inheritdoc />
    public float MaxThrustAt(double pressure)
        => Internal.MaxThrustAt(pressure);

    /// <inheritdoc />
    public float SpecificImpulseAt(double pressure)
        => Internal.SpecificImpulseAt(pressure);

    /// <inheritdoc />
    public void ToggleMode()
        => Internal.ToggleMode();
}
