// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseFairing = KRPC.Client.Services.SpaceCenter.Fairing;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Fairing object.
/// </summary>
public class Fairing
{
    internal BaseFairing Internal { get; }

    internal Fairing(BaseFairing fairing)
    {
        ArgumentNullException.ThrowIfNull(fairing);
        Internal = fairing;
    }

    /// <inheritdoc />
    public bool Jettisoned
        => Internal.Jettisoned;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public void Jettison()
        => Internal.Jettison();
}
