// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseFlight = KRPC.Client.Services.SpaceCenter.Flight;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Flight object.
/// </summary>
public class Flight
{
    internal BaseFlight Internal { get; }

    internal Flight(BaseFlight flight)
    {
        ArgumentNullException.ThrowIfNull(flight);
        Internal = flight;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> AerodynamicForce
        => Internal.AerodynamicForce;

    /// <inheritdoc />
    public float AngleOfAttack
        => Internal.AngleOfAttack;

    /// <inheritdoc />
    public Tuple<double, double, double> AntiNormal
        => Internal.AntiNormal;

    /// <inheritdoc />
    public Tuple<double, double, double> AntiRadial
        => Internal.AntiRadial;

    /// <inheritdoc />
    public float AtmosphereDensity
        => Internal.AtmosphereDensity;

    /// <inheritdoc />
    public float BallisticCoefficient
        => Internal.BallisticCoefficient;

    /// <inheritdoc />
    public double BedrockAltitude
        => Internal.BedrockAltitude;

    /// <inheritdoc />
    public Tuple<double, double, double> CenterOfMass
        => Internal.CenterOfMass;

    /// <inheritdoc />
    public Tuple<double, double, double> Direction
        => Internal.Direction;

    /// <inheritdoc />
    public Tuple<double, double, double> Drag
        => Internal.Drag;

    /// <inheritdoc />
    public float DragCoefficient
        => Internal.DragCoefficient;

    /// <inheritdoc />
    public float DynamicPressure
        => Internal.DynamicPressure;

    /// <inheritdoc />
    public double Elevation
        => Internal.Elevation;

    /// <inheritdoc />
    public float EquivalentAirSpeed
        => Internal.EquivalentAirSpeed;

    /// <inheritdoc />
    public float GForce
        => Internal.GForce;

    /// <inheritdoc />
    public float Heading
        => Internal.Heading;

    /// <inheritdoc />
    public double HorizontalSpeed
        => Internal.HorizontalSpeed;

    /// <inheritdoc />
    public double Latitude
        => Internal.Latitude;

    /// <inheritdoc />
    public Tuple<double, double, double> Lift
        => Internal.Lift;

    /// <inheritdoc />
    public float LiftCoefficient
        => Internal.LiftCoefficient;

    /// <inheritdoc />
    public double Longitude
        => Internal.Longitude;

    /// <inheritdoc />
    public float Mach
        => Internal.Mach;

    /// <inheritdoc />
    public double MeanAltitude
        => Internal.MeanAltitude;

    /// <inheritdoc />
    public Tuple<double, double, double> Normal
        => Internal.Normal;

    /// <inheritdoc />
    public float Pitch
        => Internal.Pitch;

    /// <inheritdoc />
    public Tuple<double, double, double> Prograde
        => Internal.Prograde;

    /// <inheritdoc />
    public Tuple<double, double, double> Radial
        => Internal.Radial;

    /// <inheritdoc />
    public Tuple<double, double, double> Retrograde
        => Internal.Retrograde;

    /// <inheritdoc />
    public float ReynoldsNumber
        => Internal.ReynoldsNumber;

    /// <inheritdoc />
    public float Roll
        => Internal.Roll;

    /// <inheritdoc />
    public Tuple<double, double, double, double> Rotation
        => Internal.Rotation;

    /// <inheritdoc />
    public float SideslipAngle
        => Internal.SideslipAngle;

    /// <inheritdoc />
    public double Speed
        => Internal.Speed;

    /// <inheritdoc />
    public float SpeedOfSound
        => Internal.SpeedOfSound;

    /// <inheritdoc />
    public float StallFraction
        => Internal.StallFraction;

    /// <inheritdoc />
    public float StaticAirTemperature
        => Internal.StaticAirTemperature;

    /// <inheritdoc />
    public float StaticPressure
        => Internal.StaticPressure;

    /// <inheritdoc />
    public float StaticPressureAtMSL
        => Internal.StaticPressureAtMSL;

    /// <inheritdoc />
    public double SurfaceAltitude
        => Internal.SurfaceAltitude;

    /// <inheritdoc />
    public float TerminalVelocity
        => Internal.TerminalVelocity;

    /// <inheritdoc />
    public float ThrustSpecificFuelConsumption
        => Internal.ThrustSpecificFuelConsumption;

    /// <inheritdoc />
    public float TotalAirTemperature
        => Internal.TotalAirTemperature;

    /// <inheritdoc />
    public float TrueAirSpeed
        => Internal.TrueAirSpeed;

    /// <inheritdoc />
    public Tuple<double, double, double> Velocity
        => Internal.Velocity;

    /// <inheritdoc />
    public double VerticalSpeed
        => Internal.VerticalSpeed;

    /// <inheritdoc />
    public Tuple<double, double, double> SimulateAerodynamicForceAt(CelestialBody body, Tuple<double, double, double> position, Tuple<double, double, double> velocity)
        => Internal.SimulateAerodynamicForceAt(body.Internal, position, velocity);
}
