// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseForce = KRPC.Client.Services.SpaceCenter.Force;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Force object.
/// </summary>
public class Force
{
    internal BaseForce Internal { get; }

    internal Force(BaseForce force)
    {
        ArgumentNullException.ThrowIfNull(force);
        Internal = force;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> ForceVector
    {
        get => Internal.ForceVector;
        set => Internal.ForceVector = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public Tuple<double, double, double> Position
    {
        get => Internal.Position;
        set => Internal.Position = value;
    }

    /// <inheritdoc />
    public ReferenceFrame ReferenceFrame
    {
        get => new ReferenceFrame(Internal.ReferenceFrame);
        set => Internal.ReferenceFrame = value.Internal;
    }

    /// <inheritdoc />
    public void Remove()
        => Internal.Remove();
}
