// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseIntake = KRPC.Client.Services.SpaceCenter.Intake;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Intake object.
/// </summary>
public class Intake
{
    internal BaseIntake Internal { get; }

    internal Intake(BaseIntake intake)
    {
        ArgumentNullException.ThrowIfNull(intake);
        Internal = intake;
    }

    /// <inheritdoc />
    public float Area
        => Internal.Area;

    /// <inheritdoc />
    public float Flow
        => Internal.Flow;

    /// <inheritdoc />
    public bool Open
    {
        get => Internal.Open;
        set => Internal.Open = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float Speed
        => Internal.Speed;
}
