// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseLaunchSite = KRPC.Client.Services.SpaceCenter.LaunchSite;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter LaunchSite object.
/// </summary>
public class LaunchSite
{
    internal BaseLaunchSite Internal { get; }

    internal LaunchSite(BaseLaunchSite launchSite)
    {
        ArgumentNullException.ThrowIfNull(launchSite);
        Internal = launchSite;
    }

    /// <inheritdoc />
    public CelestialBody Body
        => new CelestialBody(Internal.Body);

    /// <inheritdoc />
    public EditorFacility EditorFacility
        => Internal.EditorFacility;

    /// <inheritdoc />
    public string Name
        => Internal.Name;
}
