// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseLaunchClamp = KRPC.Client.Services.SpaceCenter.LaunchClamp;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter LaunchClamp object.
/// </summary>
public class LaunchClamp
{
    internal BaseLaunchClamp Internal { get; }

    internal LaunchClamp(BaseLaunchClamp launchClamp)
    {
        ArgumentNullException.ThrowIfNull(launchClamp);
        Internal = launchClamp;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public void Release()
        => Internal.Release();
}
