// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseLeg = KRPC.Client.Services.SpaceCenter.Leg;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Leg object.
/// </summary>
public class Leg
{
    internal BaseLeg Internal { get; }

    internal Leg(BaseLeg leg)
    {
        ArgumentNullException.ThrowIfNull(leg);
        Internal = leg;
    }

    /// <inheritdoc />
    public bool Deployable
        => Internal.Deployable;

    /// <inheritdoc />
    public bool Deployed
    {
        get => Internal.Deployed;
        set => Internal.Deployed = value;
    }

    /// <inheritdoc />
    public bool IsGrounded
        => Internal.IsGrounded;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public LegState State
        => Internal.State;
}
