// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseLight = KRPC.Client.Services.SpaceCenter.Light;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Light object.
/// </summary>
public class Light
{
    internal BaseLight Internal { get; }

    internal Light(BaseLight light)
    {
        ArgumentNullException.ThrowIfNull(light);
        Internal = light;
    }

    /// <inheritdoc />
    public bool Active
    {
        get => Internal.Active;
        set => Internal.Active = value;
    }

    /// <inheritdoc />
    public bool Blink
    {
        get => Internal.Blink;
        set => Internal.Blink = value;
    }

    /// <inheritdoc />
    public float BlinkRate
    {
        get => Internal.BlinkRate;
        set => Internal.BlinkRate = value;
    }

    /// <inheritdoc />
    public Tuple<float, float, float> Color
    {
        get => Internal.Color;
        set => Internal.Color = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float PowerUsage
        => Internal.PowerUsage;
}
