// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseModule = KRPC.Client.Services.SpaceCenter.Module;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Module object.
/// </summary>
public class Module
{
    internal BaseModule Internal { get; }

    internal Module(BaseModule module)
    {
        ArgumentNullException.ThrowIfNull(module);
        Internal = module;
    }

    /// <inheritdoc />
    public IList<string> Actions
        => Internal.Actions;

    /// <inheritdoc />
    public IList<string> ActionsById
        => Internal.ActionsById;

    /// <inheritdoc />
    public IList<string> Events
        => Internal.Events;

    /// <inheritdoc />
    public IList<string> EventsById
        => Internal.EventsById;

    /// <inheritdoc />
    public IDictionary<string, string> Fields
        => Internal.Fields;

    /// <inheritdoc />
    public IDictionary<string, string> FieldsById
        => Internal.FieldsById;

    /// <inheritdoc />
    public string Name
        => Internal.Name;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public string GetField(string name)
        => Internal.GetField(name);

    /// <inheritdoc />
    public string GetFieldById(string id)
        => Internal.GetFieldById(id);

    /// <inheritdoc />
    public bool HasAction(string name)
        => Internal.HasAction(name);

    /// <inheritdoc />
    public bool HasActionWithId(string id)
        => Internal.HasActionWithId(id);

    /// <inheritdoc />
    public bool HasEvent(string name)
        => Internal.HasEvent(name);

    /// <inheritdoc />
    public bool HasEventWithId(string id)
        => Internal.HasEventWithId(id);

    /// <inheritdoc />
    public bool HasField(string name)
        => Internal.HasField(name);

    /// <inheritdoc />
    public bool HasFieldWithId(string id)
        => Internal.HasFieldWithId(id);

    /// <inheritdoc />
    public void ResetField(string name)
        => Internal.ResetField(name);

    /// <inheritdoc />
    public void ResetFieldById(string id)
        => Internal.ResetFieldById(id);

    /// <inheritdoc />
    public void SetAction(string name, bool value = true)
        => Internal.SetAction(name, value);

    /// <inheritdoc />
    public void SetActionById(string id, bool value = true)
        => Internal.SetActionById(id, value);

    /// <inheritdoc />
    public void SetFieldBool(string name, bool value)
        => Internal.SetFieldBool(name, value);

    /// <inheritdoc />
    public void SetFieldBoolById(string id, bool value)
        => Internal.SetFieldBoolById(id, value);

    /// <inheritdoc />
    public void SetFieldFloat(string name, float value)
        => Internal.SetFieldFloat(name, value);

    /// <inheritdoc />
    public void SetFieldFloatById(string id, float value)
        => Internal.SetFieldFloatById(id, value);

    /// <inheritdoc />
    public void SetFieldInt(string name, int value)
        => Internal.SetFieldInt(name, value);

    /// <inheritdoc />
    public void SetFieldIntById(string id, int value)
        => Internal.SetFieldIntById(id, value);

    /// <inheritdoc />
    public void SetFieldString(string name, string value)
        => Internal.SetFieldString(name, value);

    /// <inheritdoc />
    public void SetFieldStringById(string id, string value)
        => Internal.SetFieldStringById(id, value);

    /// <inheritdoc />
    public void TriggerEvent(string name)
        => Internal.TriggerEvent(name);

    /// <inheritdoc />
    public void TriggerEventById(string id)
        => Internal.TriggerEventById(id);
}
