// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseNode = KRPC.Client.Services.SpaceCenter.Node;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Node object.
/// </summary>
public class Node
{
    internal BaseNode Internal { get; }

    internal Node(BaseNode node)
    {
        ArgumentNullException.ThrowIfNull(node);
        Internal = node;
    }

    /// <inheritdoc />
    public double DeltaV
    {
        get => Internal.DeltaV;
        set => Internal.DeltaV = value;
    }

    /// <inheritdoc />
    public double Normal
    {
        get => Internal.Normal;
        set => Internal.Normal = value;
    }

    /// <inheritdoc />
    public Orbit Orbit
        => new Orbit(Internal.Orbit);

    /// <inheritdoc />
    public ReferenceFrame OrbitalReferenceFrame
        => new ReferenceFrame(Internal.OrbitalReferenceFrame);

    /// <inheritdoc />
    public double Prograde
    {
        get => Internal.Prograde;
        set => Internal.Prograde = value;
    }

    /// <inheritdoc />
    public double Radial
    {
        get => Internal.Radial;
        set => Internal.Radial = value;
    }

    /// <inheritdoc />
    public ReferenceFrame ReferenceFrame
        => new ReferenceFrame(Internal.ReferenceFrame);

    /// <inheritdoc />
    public double RemainingDeltaV
        => Internal.RemainingDeltaV;

    /// <inheritdoc />
    public double TimeTo
        => Internal.TimeTo;

    /// <inheritdoc />
    public double UT
    {
        get => Internal.UT;
        set => Internal.UT = value;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> BurnVector(ReferenceFrame? referenceFrame = null)
        => Internal.BurnVector(referenceFrame?.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Direction(ReferenceFrame referenceFrame)
        => Internal.Direction(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Position(ReferenceFrame referenceFrame)
        => Internal.Position(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> RemainingBurnVector(ReferenceFrame? referenceFrame = null)
        => Internal.RemainingBurnVector(referenceFrame?.Internal);

    /// <inheritdoc />
    public void Remove()
        => Internal.Remove();
}
