// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseOrbit = KRPC.Client.Services.SpaceCenter.Orbit;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Orbit object.
/// </summary>
public class Orbit
{
    internal BaseOrbit Internal { get; }

    internal Orbit(BaseOrbit orbit)
    {
        ArgumentNullException.ThrowIfNull(orbit);
        Internal = orbit;
    }

    /// <inheritdoc />
    public double Apoapsis
        => Internal.Apoapsis;

    /// <inheritdoc />
    public double ApoapsisAltitude
        => Internal.ApoapsisAltitude;

    /// <inheritdoc />
    public double ArgumentOfPeriapsis
        => Internal.ArgumentOfPeriapsis;

    /// <inheritdoc />
    public CelestialBody Body
        => new CelestialBody(Internal.Body);

    /// <inheritdoc />
    public double EccentricAnomaly
        => Internal.EccentricAnomaly;

    /// <inheritdoc />
    public double Eccentricity
        => Internal.Eccentricity;

    /// <inheritdoc />
    public double Epoch
        => Internal.Epoch;

    /// <inheritdoc />
    public double Inclination
        => Internal.Inclination;

    /// <inheritdoc />
    public double LongitudeOfAscendingNode
        => Internal.LongitudeOfAscendingNode;

    /// <inheritdoc />
    public double MeanAnomaly
        => Internal.MeanAnomaly;

    /// <inheritdoc />
    public double MeanAnomalyAtEpoch
        => Internal.MeanAnomalyAtEpoch;

    /// <inheritdoc />
    public Orbit NextOrbit
        => new Orbit(Internal.NextOrbit);

    /// <inheritdoc />
    public double OrbitalSpeed
        => Internal.OrbitalSpeed;

    /// <inheritdoc />
    public double Periapsis
        => Internal.Periapsis;

    /// <inheritdoc />
    public double PeriapsisAltitude
        => Internal.PeriapsisAltitude;

    /// <inheritdoc />
    public double Period
        => Internal.Period;

    /// <inheritdoc />
    public double Radius
        => Internal.Radius;

    /// <inheritdoc />
    public double SemiMajorAxis
        => Internal.SemiMajorAxis;

    /// <inheritdoc />
    public double SemiMinorAxis
        => Internal.SemiMinorAxis;

    /// <inheritdoc />
    public double Speed
        => Internal.Speed;

    /// <inheritdoc />
    public double TimeToApoapsis
        => Internal.TimeToApoapsis;

    /// <inheritdoc />
    public double TimeToPeriapsis
        => Internal.TimeToPeriapsis;

    /// <inheritdoc />
    public double TimeToSOIChange
        => Internal.TimeToSOIChange;

    /// <inheritdoc />
    public double TrueAnomaly
        => Internal.TrueAnomaly;

    /// <inheritdoc />
    public double DistanceAtClosestApproach(Orbit target)
        => Internal.DistanceAtClosestApproach(target.Internal);

    /// <inheritdoc />
    public double EccentricAnomalyAtUT(double ut)
        => Internal.EccentricAnomalyAtUT(ut);

    /// <inheritdoc />
    public IList<IList<double>> ListClosestApproaches(Orbit target, int orbits)
        => Internal.ListClosestApproaches(target.Internal, orbits);

    /// <inheritdoc />
    public double MeanAnomalyAtUT(double ut)
        => Internal.MeanAnomalyAtUT(ut);

    /// <inheritdoc />
    public double OrbitalSpeedAt(double time)
        => Internal.OrbitalSpeedAt(time);

    /// <inheritdoc />
    public Tuple<double, double, double> PositionAt(double ut, ReferenceFrame referenceFrame)
        => Internal.PositionAt(ut, referenceFrame.Internal);

    /// <inheritdoc />
    public double RadiusAt(double ut)
        => Internal.RadiusAt(ut);

    /// <inheritdoc />
    public double RadiusAtTrueAnomaly(double trueAnomaly)
        => Internal.RadiusAtTrueAnomaly(trueAnomaly);

    /// <inheritdoc />
    public double RelativeInclination(Orbit target)
        => Internal.RelativeInclination(target.Internal);

    /// <inheritdoc />
    public double TimeOfClosestApproach(Orbit target)
        => Internal.TimeOfClosestApproach(target.Internal);

    /// <inheritdoc />
    public double TrueAnomalyAtAN(Orbit target)
        => Internal.TrueAnomalyAtAN(target.Internal);

    /// <inheritdoc />
    public double TrueAnomalyAtDN(Orbit target)
        => Internal.TrueAnomalyAtDN(target.Internal);

    /// <inheritdoc />
    public double TrueAnomalyAtRadius(double radius)
        => Internal.TrueAnomalyAtRadius(radius);

    /// <inheritdoc />
    public double TrueAnomalyAtUT(double ut)
        => Internal.TrueAnomalyAtUT(ut);

    /// <inheritdoc />
    public double UTAtTrueAnomaly(double trueAnomaly)
        => Internal.UTAtTrueAnomaly(trueAnomaly);

    /// <inheritdoc />
    public static Tuple<double, double, double> ReferencePlaneDirection(IConnection connection, ReferenceFrame referenceFrame)
        => BaseOrbit.ReferencePlaneDirection(connection, referenceFrame.Internal);

    /// <inheritdoc />
    public static Tuple<double, double, double> ReferencePlaneNormal(IConnection connection, ReferenceFrame referenceFrame)
        => BaseOrbit.ReferencePlaneNormal(connection, referenceFrame.Internal);
}
