// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseParachute = KRPC.Client.Services.SpaceCenter.Parachute;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Parachute object.
/// </summary>
public class Parachute
{
    internal BaseParachute Internal { get; }

    internal Parachute(BaseParachute parachute)
    {
        ArgumentNullException.ThrowIfNull(parachute);
        Internal = parachute;
    }

    /// <inheritdoc />
    public bool Armed
        => Internal.Armed;

    /// <inheritdoc />
    public float DeployAltitude
    {
        get => Internal.DeployAltitude;
        set => Internal.DeployAltitude = value;
    }

    /// <inheritdoc />
    public float DeployMinPressure
    {
        get => Internal.DeployMinPressure;
        set => Internal.DeployMinPressure = value;
    }

    /// <inheritdoc />
    public bool Deployed
        => Internal.Deployed;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public ParachuteState State
        => Internal.State;

    /// <inheritdoc />
    public void Arm()
        => Internal.Arm();

    /// <inheritdoc />
    public void Cut()
        => Internal.Cut();

    /// <inheritdoc />
    public void Deploy()
        => Internal.Deploy();
}
