// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseParts = KRPC.Client.Services.SpaceCenter.Parts;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Parts object.
/// </summary>
public class Parts
{
    internal BaseParts Internal { get; }

    internal Parts(BaseParts parts)
    {
        ArgumentNullException.ThrowIfNull(parts);
        Internal = parts;
    }

    /// <inheritdoc />
    public IList<Part> All
        => Internal.All.Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public IList<Antenna> Antennas
        => Internal.Antennas.Select(item => new Antenna(item)).ToList();

    /// <inheritdoc />
    public IList<CargoBay> CargoBays
        => Internal.CargoBays.Select(item => new CargoBay(item)).ToList();

    /// <inheritdoc />
    public IList<ControlSurface> ControlSurfaces
        => Internal.ControlSurfaces.Select(item => new ControlSurface(item)).ToList();

    /// <inheritdoc />
    public Part Controlling
    {
        get => new Part(Internal.Controlling);
        set => Internal.Controlling = value.Internal;
    }

    /// <inheritdoc />
    public IList<Decoupler> Decouplers
        => Internal.Decouplers.Select(item => new Decoupler(item)).ToList();

    /// <inheritdoc />
    public IList<DockingPort> DockingPorts
        => Internal.DockingPorts.Select(item => new DockingPort(item)).ToList();

    /// <inheritdoc />
    public IList<Engine> Engines
        => Internal.Engines.Select(item => new Engine(item)).ToList();

    /// <inheritdoc />
    public IList<Experiment> Experiments
        => Internal.Experiments.Select(item => new Experiment(item)).ToList();

    /// <inheritdoc />
    public IList<Fairing> Fairings
        => Internal.Fairings.Select(item => new Fairing(item)).ToList();

    /// <inheritdoc />
    public IList<Intake> Intakes
        => Internal.Intakes.Select(item => new Intake(item)).ToList();

    /// <inheritdoc />
    public IList<LaunchClamp> LaunchClamps
        => Internal.LaunchClamps.Select(item => new LaunchClamp(item)).ToList();

    /// <inheritdoc />
    public IList<Leg> Legs
        => Internal.Legs.Select(item => new Leg(item)).ToList();

    /// <inheritdoc />
    public IList<Light> Lights
        => Internal.Lights.Select(item => new Light(item)).ToList();

    /// <inheritdoc />
    public IList<Parachute> Parachutes
        => Internal.Parachutes.Select(item => new Parachute(item)).ToList();

    /// <inheritdoc />
    public IList<RCS> RCS
        => Internal.RCS.Select(item => new RCS(item)).ToList();

    /// <inheritdoc />
    public IList<Radiator> Radiators
        => Internal.Radiators.Select(item => new Radiator(item)).ToList();

    /// <inheritdoc />
    public IList<ReactionWheel> ReactionWheels
        => Internal.ReactionWheels.Select(item => new ReactionWheel(item)).ToList();

    /// <inheritdoc />
    public IList<ResourceConverter> ResourceConverters
        => Internal.ResourceConverters.Select(item => new ResourceConverter(item)).ToList();

    /// <inheritdoc />
    public IList<ResourceDrain> ResourceDrains
        => Internal.ResourceDrains.Select(item => new ResourceDrain(item)).ToList();

    /// <inheritdoc />
    public IList<ResourceHarvester> ResourceHarvesters
        => Internal.ResourceHarvesters.Select(item => new ResourceHarvester(item)).ToList();

    /// <inheritdoc />
    public IList<RoboticHinge> RoboticHinges
        => Internal.RoboticHinges.Select(item => new RoboticHinge(item)).ToList();

    /// <inheritdoc />
    public IList<RoboticPiston> RoboticPistons
        => Internal.RoboticPistons.Select(item => new RoboticPiston(item)).ToList();

    /// <inheritdoc />
    public IList<RoboticRotation> RoboticRotations
        => Internal.RoboticRotations.Select(item => new RoboticRotation(item)).ToList();

    /// <inheritdoc />
    public IList<RoboticRotor> RoboticRotors
        => Internal.RoboticRotors.Select(item => new RoboticRotor(item)).ToList();

    /// <inheritdoc />
    public Part Root
        => new Part(Internal.Root);

    /// <inheritdoc />
    public IList<Sensor> Sensors
        => Internal.Sensors.Select(item => new Sensor(item)).ToList();

    /// <inheritdoc />
    public IList<SolarPanel> SolarPanels
        => Internal.SolarPanels.Select(item => new SolarPanel(item)).ToList();

    /// <inheritdoc />
    public IList<Wheel> Wheels
        => Internal.Wheels.Select(item => new Wheel(item)).ToList();

    /// <inheritdoc />
    public IList<Part> InDecoupleStage(int stage)
        => Internal.InDecoupleStage(stage).Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public IList<Part> InStage(int stage)
        => Internal.InStage(stage).Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public IList<Module> ModulesWithName(string moduleName)
        => Internal.ModulesWithName(moduleName).Select(item => new Module(item)).ToList();

    /// <inheritdoc />
    public IList<Part> WithModule(string moduleName)
        => Internal.WithModule(moduleName).Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public IList<Part> WithName(string name)
        => Internal.WithName(name).Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public IList<Part> WithTag(string tag)
        => Internal.WithTag(tag).Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public IList<Part> WithTitle(string title)
        => Internal.WithTitle(title).Select(item => new Part(item)).ToList();
}
