// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BasePart = KRPC.Client.Services.SpaceCenter.Part;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Part object.
/// </summary>
public class Part
{
    internal BasePart Internal { get; }

    internal Part(BasePart part)
    {
        ArgumentNullException.ThrowIfNull(part);
        Internal = part;
    }

    /// <inheritdoc />
    public Antenna Antenna
        => new Antenna(Internal.Antenna);

    /// <inheritdoc />
    public AutoStrutMode AutoStrutMode
        => Internal.AutoStrutMode;

    /// <inheritdoc />
    public uint AvailableSeats
        => Internal.AvailableSeats;

    /// <inheritdoc />
    public bool AxiallyAttached
        => Internal.AxiallyAttached;

    /// <inheritdoc />
    public CargoBay CargoBay
        => new CargoBay(Internal.CargoBay);

    /// <inheritdoc />
    public ReferenceFrame CenterOfMassReferenceFrame
        => new ReferenceFrame(Internal.CenterOfMassReferenceFrame);

    /// <inheritdoc />
    public IList<Part> Children
        => Internal.Children.Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public ControlSurface ControlSurface
        => new ControlSurface(Internal.ControlSurface);

    /// <inheritdoc />
    public double Cost
        => Internal.Cost;

    /// <inheritdoc />
    public bool Crossfeed
        => Internal.Crossfeed;

    /// <inheritdoc />
    public int DecoupleStage
        => Internal.DecoupleStage;

    /// <inheritdoc />
    public Decoupler Decoupler
        => new Decoupler(Internal.Decoupler);

    /// <inheritdoc />
    public DockingPort DockingPort
        => new DockingPort(Internal.DockingPort);

    /// <inheritdoc />
    public double DryMass
        => Internal.DryMass;

    /// <inheritdoc />
    public float DynamicPressure
        => Internal.DynamicPressure;

    /// <inheritdoc />
    public Engine Engine
        => new Engine(Internal.Engine);

    /// <inheritdoc />
    public Experiment Experiment
        => new Experiment(Internal.Experiment);

    /// <inheritdoc />
    public IList<Experiment> Experiments
        => Internal.Experiments.Select(item => new Experiment(item)).ToList();

    /// <inheritdoc />
    public Fairing Fairing
        => new Fairing(Internal.Fairing);

    /// <inheritdoc />
    public string FlagURL
    {
        get => Internal.FlagURL;
        set => Internal.FlagURL = value;
    }

    /// <inheritdoc />
    public IList<Part> FuelLinesFrom
        => Internal.FuelLinesFrom.Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public IList<Part> FuelLinesTo
        => Internal.FuelLinesTo.Select(item => new Part(item)).ToList();

    /// <inheritdoc />
    public bool Glow
    {
        set => Internal.Glow = value;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> HighlightColor
    {
        get => Internal.HighlightColor;
        set => Internal.HighlightColor = value;
    }

    /// <inheritdoc />
    public bool Highlighted
    {
        get => Internal.Highlighted;
        set => Internal.Highlighted = value;
    }

    /// <inheritdoc />
    public double ImpactTolerance
        => Internal.ImpactTolerance;

    /// <inheritdoc />
    public IList<double> InertiaTensor
        => Internal.InertiaTensor;

    /// <inheritdoc />
    public Intake Intake
        => new Intake(Internal.Intake);

    /// <inheritdoc />
    public bool IsFuelLine
        => Internal.IsFuelLine;

    /// <inheritdoc />
    public LaunchClamp LaunchClamp
        => new LaunchClamp(Internal.LaunchClamp);

    /// <inheritdoc />
    public Leg Leg
        => new Leg(Internal.Leg);

    /// <inheritdoc />
    public Light Light
        => new Light(Internal.Light);

    /// <inheritdoc />
    public double Mass
        => Internal.Mass;

    /// <inheritdoc />
    public bool Massless
        => Internal.Massless;

    /// <inheritdoc />
    public double MaxSkinTemperature
        => Internal.MaxSkinTemperature;

    /// <inheritdoc />
    public double MaxTemperature
        => Internal.MaxTemperature;

    /// <inheritdoc />
    public IList<Module> Modules
        => Internal.Modules.Select(item => new Module(item)).ToList();

    /// <inheritdoc />
    public Tuple<double, double, double> MomentOfInertia
        => Internal.MomentOfInertia;

    /// <inheritdoc />
    public string Name
        => Internal.Name;

    /// <inheritdoc />
    public Parachute Parachute
        => new Parachute(Internal.Parachute);

    /// <inheritdoc />
    public Part Parent
        => new Part(Internal.Parent);

    /// <inheritdoc />
    public RCS RCS
        => new RCS(Internal.RCS);

    /// <inheritdoc />
    public bool RadiallyAttached
        => Internal.RadiallyAttached;

    /// <inheritdoc />
    public Radiator Radiator
        => new Radiator(Internal.Radiator);

    /// <inheritdoc />
    public ReactionWheel ReactionWheel
        => new ReactionWheel(Internal.ReactionWheel);

    /// <inheritdoc />
    public ReferenceFrame ReferenceFrame
        => new ReferenceFrame(Internal.ReferenceFrame);

    /// <inheritdoc />
    public ResourceConverter ResourceConverter
        => new ResourceConverter(Internal.ResourceConverter);

    /// <inheritdoc />
    public ResourceDrain ResourceDrain
        => new ResourceDrain(Internal.ResourceDrain);

    /// <inheritdoc />
    public ResourceHarvester ResourceHarvester
        => new ResourceHarvester(Internal.ResourceHarvester);

    /// <inheritdoc />
    public Resources Resources
        => new Resources(Internal.Resources);

    /// <inheritdoc />
    public RoboticController RoboticController
        => new RoboticController(Internal.RoboticController);

    /// <inheritdoc />
    public RoboticHinge RoboticHinge
        => new RoboticHinge(Internal.RoboticHinge);

    /// <inheritdoc />
    public RoboticPiston RoboticPiston
        => new RoboticPiston(Internal.RoboticPiston);

    /// <inheritdoc />
    public RoboticRotation RoboticRotation
        => new RoboticRotation(Internal.RoboticRotation);

    /// <inheritdoc />
    public RoboticRotor RoboticRotor
        => new RoboticRotor(Internal.RoboticRotor);

    /// <inheritdoc />
    public Sensor Sensor
        => new Sensor(Internal.Sensor);

    /// <inheritdoc />
    public bool Shielded
        => Internal.Shielded;

    /// <inheritdoc />
    public double SkinTemperature
        => Internal.SkinTemperature;

    /// <inheritdoc />
    public SolarPanel SolarPanel
        => new SolarPanel(Internal.SolarPanel);

    /// <inheritdoc />
    public int Stage
        => Internal.Stage;

    /// <inheritdoc />
    public string Tag
    {
        get => Internal.Tag;
        set => Internal.Tag = value;
    }

    /// <inheritdoc />
    public double Temperature
        => Internal.Temperature;

    /// <inheritdoc />
    public float ThermalConductionFlux
        => Internal.ThermalConductionFlux;

    /// <inheritdoc />
    public float ThermalConvectionFlux
        => Internal.ThermalConvectionFlux;

    /// <inheritdoc />
    public float ThermalInternalFlux
        => Internal.ThermalInternalFlux;

    /// <inheritdoc />
    public float ThermalMass
        => Internal.ThermalMass;

    /// <inheritdoc />
    public float ThermalRadiationFlux
        => Internal.ThermalRadiationFlux;

    /// <inheritdoc />
    public float ThermalResourceMass
        => Internal.ThermalResourceMass;

    /// <inheritdoc />
    public float ThermalSkinMass
        => Internal.ThermalSkinMass;

    /// <inheritdoc />
    public float ThermalSkinToInternalFlux
        => Internal.ThermalSkinToInternalFlux;

    /// <inheritdoc />
    public string Title
        => Internal.Title;

    /// <inheritdoc />
    public Vessel Vessel
        => new Vessel(Internal.Vessel);

    /// <inheritdoc />
    public Wheel Wheel
        => new Wheel(Internal.Wheel);

    /// <inheritdoc />
    public Force AddForce(Tuple<double, double, double> force, Tuple<double, double, double> position, ReferenceFrame referenceFrame)
        => new Force(Internal.AddForce(force, position, referenceFrame.Internal));

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> BoundingBox(ReferenceFrame referenceFrame)
        => Internal.BoundingBox(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> CenterOfMass(ReferenceFrame referenceFrame)
        => Internal.CenterOfMass(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Direction(ReferenceFrame referenceFrame)
        => Internal.Direction(referenceFrame.Internal);

    /// <inheritdoc />
    public void InstantaneousForce(Tuple<double, double, double> force, Tuple<double, double, double> position, ReferenceFrame referenceFrame)
        => Internal.InstantaneousForce(force, position, referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Position(ReferenceFrame referenceFrame)
        => Internal.Position(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double, double> Rotation(ReferenceFrame referenceFrame)
        => Internal.Rotation(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Velocity(ReferenceFrame referenceFrame)
        => Internal.Velocity(referenceFrame.Internal);
}
