// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BasePropellant = KRPC.Client.Services.SpaceCenter.Propellant;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Propellant object.
/// </summary>
public class Propellant
{
    internal BasePropellant Internal { get; }

    internal Propellant(BasePropellant propellant)
    {
        ArgumentNullException.ThrowIfNull(propellant);
        Internal = propellant;
    }

    /// <inheritdoc />
    public double CurrentAmount
        => Internal.CurrentAmount;

    /// <inheritdoc />
    public double CurrentRequirement
        => Internal.CurrentRequirement;

    /// <inheritdoc />
    public bool DrawStackGauge
        => Internal.DrawStackGauge;

    /// <inheritdoc />
    public bool IgnoreForIsp
        => Internal.IgnoreForIsp;

    /// <inheritdoc />
    public bool IgnoreForThrustCurve
        => Internal.IgnoreForThrustCurve;

    /// <inheritdoc />
    public bool IsDeprived
        => Internal.IsDeprived;

    /// <inheritdoc />
    public string Name
        => Internal.Name;

    /// <inheritdoc />
    public float Ratio
        => Internal.Ratio;

    /// <inheritdoc />
    public double TotalResourceAvailable
        => Internal.TotalResourceAvailable;

    /// <inheritdoc />
    public double TotalResourceCapacity
        => Internal.TotalResourceCapacity;
}
