// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseRadiator = KRPC.Client.Services.SpaceCenter.Radiator;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Radiator object.
/// </summary>
public class Radiator
{
    internal BaseRadiator Internal { get; }

    internal Radiator(BaseRadiator radiator)
    {
        ArgumentNullException.ThrowIfNull(radiator);
        Internal = radiator;
    }

    /// <inheritdoc />
    public bool Deployable
        => Internal.Deployable;

    /// <inheritdoc />
    public bool Deployed
    {
        get => Internal.Deployed;
        set => Internal.Deployed = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public RadiatorState State
        => Internal.State;
}
