// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseRCS = KRPC.Client.Services.SpaceCenter.RCS;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter RCS object.
/// </summary>
public class RCS
{
    internal BaseRCS Internal { get; }

    internal RCS(BaseRCS rCS)
    {
        ArgumentNullException.ThrowIfNull(rCS);
        Internal = rCS;
    }

    /// <inheritdoc />
    public bool Active
        => Internal.Active;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableForce
        => Internal.AvailableForce;

    /// <inheritdoc />
    public float AvailableThrust
        => Internal.AvailableThrust;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableTorque
        => Internal.AvailableTorque;

    /// <inheritdoc />
    public bool Enabled
    {
        get => Internal.Enabled;
        set => Internal.Enabled = value;
    }

    /// <inheritdoc />
    public bool ForwardEnabled
    {
        get => Internal.ForwardEnabled;
        set => Internal.ForwardEnabled = value;
    }

    /// <inheritdoc />
    public bool HasFuel
        => Internal.HasFuel;

    /// <inheritdoc />
    public float KerbinSeaLevelSpecificImpulse
        => Internal.KerbinSeaLevelSpecificImpulse;

    /// <inheritdoc />
    public float MaxThrust
        => Internal.MaxThrust;

    /// <inheritdoc />
    public float MaxVacuumThrust
        => Internal.MaxVacuumThrust;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public bool PitchEnabled
    {
        get => Internal.PitchEnabled;
        set => Internal.PitchEnabled = value;
    }

    /// <inheritdoc />
    public IDictionary<string, float> PropellantRatios
        => Internal.PropellantRatios;

    /// <inheritdoc />
    public IList<string> Propellants
        => Internal.Propellants;

    /// <inheritdoc />
    public bool RightEnabled
    {
        get => Internal.RightEnabled;
        set => Internal.RightEnabled = value;
    }

    /// <inheritdoc />
    public bool RollEnabled
    {
        get => Internal.RollEnabled;
        set => Internal.RollEnabled = value;
    }

    /// <inheritdoc />
    public float SpecificImpulse
        => Internal.SpecificImpulse;

    /// <inheritdoc />
    public float ThrustLimit
    {
        get => Internal.ThrustLimit;
        set => Internal.ThrustLimit = value;
    }

    /// <inheritdoc />
    public IList<Thruster> Thrusters
        => Internal.Thrusters.Select(item => new Thruster(item)).ToList();

    /// <inheritdoc />
    public bool UpEnabled
    {
        get => Internal.UpEnabled;
        set => Internal.UpEnabled = value;
    }

    /// <inheritdoc />
    public float VacuumSpecificImpulse
        => Internal.VacuumSpecificImpulse;

    /// <inheritdoc />
    public bool YawEnabled
    {
        get => Internal.YawEnabled;
        set => Internal.YawEnabled = value;
    }
}
