// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseReactionWheel = KRPC.Client.Services.SpaceCenter.ReactionWheel;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ReactionWheel object.
/// </summary>
public class ReactionWheel
{
    internal BaseReactionWheel Internal { get; }

    internal ReactionWheel(BaseReactionWheel reactionWheel)
    {
        ArgumentNullException.ThrowIfNull(reactionWheel);
        Internal = reactionWheel;
    }

    /// <inheritdoc />
    public bool Active
    {
        get => Internal.Active;
        set => Internal.Active = value;
    }

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableTorque
        => Internal.AvailableTorque;

    /// <inheritdoc />
    public bool Broken
        => Internal.Broken;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> MaxTorque
        => Internal.MaxTorque;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);
}
