// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseResourceConverter = KRPC.Client.Services.SpaceCenter.ResourceConverter;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ResourceConverter object.
/// </summary>
public class ResourceConverter
{
    internal BaseResourceConverter Internal { get; }

    internal ResourceConverter(BaseResourceConverter resourceConverter)
    {
        ArgumentNullException.ThrowIfNull(resourceConverter);
        Internal = resourceConverter;
    }

    /// <inheritdoc />
    public float CoreTemperature
        => Internal.CoreTemperature;

    /// <inheritdoc />
    public int Count
        => Internal.Count;

    /// <inheritdoc />
    public float OptimumCoreTemperature
        => Internal.OptimumCoreTemperature;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float ThermalEfficiency
        => Internal.ThermalEfficiency;

    /// <inheritdoc />
    public bool Active(int index)
        => Internal.Active(index);

    /// <inheritdoc />
    public IList<string> Inputs(int index)
        => Internal.Inputs(index);

    /// <inheritdoc />
    public string Name(int index)
        => Internal.Name(index);

    /// <inheritdoc />
    public IList<string> Outputs(int index)
        => Internal.Outputs(index);

    /// <inheritdoc />
    public void Start(int index)
        => Internal.Start(index);

    /// <inheritdoc />
    public ResourceConverterState State(int index)
        => Internal.State(index);

    /// <inheritdoc />
    public string StatusInfo(int index)
        => Internal.StatusInfo(index);

    /// <inheritdoc />
    public void Stop(int index)
        => Internal.Stop(index);
}
