// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseResources = KRPC.Client.Services.SpaceCenter.Resources;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Resources object.
/// </summary>
public class Resources
{
    internal BaseResources Internal { get; }

    internal Resources(BaseResources resources)
    {
        ArgumentNullException.ThrowIfNull(resources);
        Internal = resources;
    }

    /// <inheritdoc />
    public IList<Resource> All
        => Internal.All.Select(item => new Resource(item)).ToList();

    /// <inheritdoc />
    public bool Enabled
    {
        get => Internal.Enabled;
        set => Internal.Enabled = value;
    }

    /// <inheritdoc />
    public IList<string> Names
        => Internal.Names;

    /// <inheritdoc />
    public float Amount(string name)
        => Internal.Amount(name);

    /// <inheritdoc />
    public bool HasResource(string name)
        => Internal.HasResource(name);

    /// <inheritdoc />
    public float Max(string name)
        => Internal.Max(name);

    /// <inheritdoc />
    public IList<Resource> WithResource(string name)
        => Internal.WithResource(name).Select(item => new Resource(item)).ToList();

    /// <inheritdoc />
    public static float Density(IConnection connection, string name)
        => BaseResources.Density(connection, name);

    /// <inheritdoc />
    public static ResourceFlowMode FlowMode(IConnection connection, string name)
        => BaseResources.FlowMode(connection, name);
}
