// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseResourceHarvester = KRPC.Client.Services.SpaceCenter.ResourceHarvester;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ResourceHarvester object.
/// </summary>
public class ResourceHarvester
{
    internal BaseResourceHarvester Internal { get; }

    internal ResourceHarvester(BaseResourceHarvester resourceHarvester)
    {
        ArgumentNullException.ThrowIfNull(resourceHarvester);
        Internal = resourceHarvester;
    }

    /// <inheritdoc />
    public bool Active
    {
        get => Internal.Active;
        set => Internal.Active = value;
    }

    /// <inheritdoc />
    public float CoreTemperature
        => Internal.CoreTemperature;

    /// <inheritdoc />
    public bool Deployed
    {
        get => Internal.Deployed;
        set => Internal.Deployed = value;
    }

    /// <inheritdoc />
    public float ExtractionRate
        => Internal.ExtractionRate;

    /// <inheritdoc />
    public float OptimumCoreTemperature
        => Internal.OptimumCoreTemperature;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public ResourceHarvesterState State
        => Internal.State;

    /// <inheritdoc />
    public float ThermalEfficiency
        => Internal.ThermalEfficiency;
}
