// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseResourceTransfer = KRPC.Client.Services.SpaceCenter.ResourceTransfer;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ResourceTransfer object.
/// </summary>
public class ResourceTransfer
{
    internal BaseResourceTransfer Internal { get; }

    internal ResourceTransfer(BaseResourceTransfer resourceTransfer)
    {
        ArgumentNullException.ThrowIfNull(resourceTransfer);
        Internal = resourceTransfer;
    }

    /// <inheritdoc />
    public float Amount
        => Internal.Amount;

    /// <inheritdoc />
    public bool Complete
        => Internal.Complete;

    /// <inheritdoc />
    public static ResourceTransfer Start(IConnection connection, Part fromPart, Part toPart, string resource, float maxAmount)
        => new ResourceTransfer(BaseResourceTransfer.Start(connection, fromPart.Internal, toPart.Internal, resource, maxAmount));
}
