// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseResource = KRPC.Client.Services.SpaceCenter.Resource;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Resource object.
/// </summary>
public class Resource
{
    internal BaseResource Internal { get; }

    internal Resource(BaseResource resource)
    {
        ArgumentNullException.ThrowIfNull(resource);
        Internal = resource;
    }

    /// <inheritdoc />
    public float Amount
        => Internal.Amount;

    /// <inheritdoc />
    public float Density
        => Internal.Density;

    /// <inheritdoc />
    public bool Enabled
    {
        get => Internal.Enabled;
        set => Internal.Enabled = value;
    }

    /// <inheritdoc />
    public ResourceFlowMode FlowMode
        => Internal.FlowMode;

    /// <inheritdoc />
    public float Max
        => Internal.Max;

    /// <inheritdoc />
    public string Name
        => Internal.Name;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);
}
