// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseResourceDrain = KRPC.Client.Services.SpaceCenter.ResourceDrain;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ResourceDrain object.
/// </summary>
public class ResourceDrain
{
    internal BaseResourceDrain Internal { get; }

    internal ResourceDrain(BaseResourceDrain resourceDrain)
    {
        ArgumentNullException.ThrowIfNull(resourceDrain);
        Internal = resourceDrain;
    }

    /// <inheritdoc />
    public IList<Resource> AvailableResources
        => Internal.AvailableResources.Select(item => new Resource(item)).ToList();

    /// <inheritdoc />
    public DrainMode DrainMode
    {
        get => Internal.DrainMode;
        set => Internal.DrainMode = value;
    }

    /// <inheritdoc />
    public float MaxRate
        => Internal.MaxRate;

    /// <inheritdoc />
    public float MinRate
        => Internal.MinRate;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float Rate
    {
        get => Internal.Rate;
        set => Internal.Rate = value;
    }

    /// <inheritdoc />
    public bool CheckResource(Resource resource)
        => Internal.CheckResource(resource.Internal);

    /// <inheritdoc />
    public void SetResource(Resource resource, bool enabled)
        => Internal.SetResource(resource.Internal, enabled);

    /// <inheritdoc />
    public void Start()
        => Internal.Start();

    /// <inheritdoc />
    public void Stop()
        => Internal.Stop();
}
