// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseRoboticRotation = KRPC.Client.Services.SpaceCenter.RoboticRotation;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter RoboticRotation object.
/// </summary>
public class RoboticRotation
{
    internal BaseRoboticRotation Internal { get; }

    internal RoboticRotation(BaseRoboticRotation roboticRotation)
    {
        ArgumentNullException.ThrowIfNull(roboticRotation);
        Internal = roboticRotation;
    }

    /// <inheritdoc />
    public float CurrentAngle
        => Internal.CurrentAngle;

    /// <inheritdoc />
    public float Damping
    {
        get => Internal.Damping;
        set => Internal.Damping = value;
    }

    /// <inheritdoc />
    public bool Locked
    {
        get => Internal.Locked;
        set => Internal.Locked = value;
    }

    /// <inheritdoc />
    public bool MotorEngaged
    {
        get => Internal.MotorEngaged;
        set => Internal.MotorEngaged = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float Rate
    {
        get => Internal.Rate;
        set => Internal.Rate = value;
    }

    /// <inheritdoc />
    public float TargetAngle
    {
        get => Internal.TargetAngle;
        set => Internal.TargetAngle = value;
    }

    /// <inheritdoc />
    public void MoveHome()
        => Internal.MoveHome();
}
