// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseRoboticPiston = KRPC.Client.Services.SpaceCenter.RoboticPiston;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter RoboticPiston object.
/// </summary>
public class RoboticPiston
{
    internal BaseRoboticPiston Internal { get; }

    internal RoboticPiston(BaseRoboticPiston roboticPiston)
    {
        ArgumentNullException.ThrowIfNull(roboticPiston);
        Internal = roboticPiston;
    }

    /// <inheritdoc />
    public float CurrentExtension
        => Internal.CurrentExtension;

    /// <inheritdoc />
    public float Damping
    {
        get => Internal.Damping;
        set => Internal.Damping = value;
    }

    /// <inheritdoc />
    public bool Locked
    {
        get => Internal.Locked;
        set => Internal.Locked = value;
    }

    /// <inheritdoc />
    public bool MotorEngaged
    {
        get => Internal.MotorEngaged;
        set => Internal.MotorEngaged = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float Rate
    {
        get => Internal.Rate;
        set => Internal.Rate = value;
    }

    /// <inheritdoc />
    public float TargetExtension
    {
        get => Internal.TargetExtension;
        set => Internal.TargetExtension = value;
    }

    /// <inheritdoc />
    public void MoveHome()
        => Internal.MoveHome();
}
