// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseRoboticRotor = KRPC.Client.Services.SpaceCenter.RoboticRotor;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter RoboticRotor object.
/// </summary>
public class RoboticRotor
{
    internal BaseRoboticRotor Internal { get; }

    internal RoboticRotor(BaseRoboticRotor roboticRotor)
    {
        ArgumentNullException.ThrowIfNull(roboticRotor);
        Internal = roboticRotor;
    }

    /// <inheritdoc />
    public float CurrentRPM
        => Internal.CurrentRPM;

    /// <inheritdoc />
    public bool Inverted
    {
        get => Internal.Inverted;
        set => Internal.Inverted = value;
    }

    /// <inheritdoc />
    public bool Locked
    {
        get => Internal.Locked;
        set => Internal.Locked = value;
    }

    /// <inheritdoc />
    public bool MotorEngaged
    {
        get => Internal.MotorEngaged;
        set => Internal.MotorEngaged = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public float TargetRPM
    {
        get => Internal.TargetRPM;
        set => Internal.TargetRPM = value;
    }

    /// <inheritdoc />
    public float TorqueLimit
    {
        get => Internal.TorqueLimit;
        set => Internal.TorqueLimit = value;
    }
}
