// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseRoboticController = KRPC.Client.Services.SpaceCenter.RoboticController;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter RoboticController object.
/// </summary>
public class RoboticController
{
    internal BaseRoboticController Internal { get; }

    internal RoboticController(BaseRoboticController roboticController)
    {
        ArgumentNullException.ThrowIfNull(roboticController);
        Internal = roboticController;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public bool AddAxis(Module module, string fieldName)
        => Internal.AddAxis(module.Internal, fieldName);

    /// <inheritdoc />
    public bool AddKeyFrame(Module module, string fieldName, float time, float value)
        => Internal.AddKeyFrame(module.Internal, fieldName, time, value);

    /// <inheritdoc />
    public IList<IList<string>> Axes()
        => Internal.Axes();

    /// <inheritdoc />
    public bool ClearAxis(Module module, string fieldName)
        => Internal.ClearAxis(module.Internal, fieldName);

    /// <inheritdoc />
    public bool HasPart(Part part)
        => Internal.HasPart(part.Internal);
}
