// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseScienceSubject = KRPC.Client.Services.SpaceCenter.ScienceSubject;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter ScienceSubject object.
/// </summary>
public class ScienceSubject
{
    internal BaseScienceSubject Internal { get; }

    internal ScienceSubject(BaseScienceSubject scienceSubject)
    {
        ArgumentNullException.ThrowIfNull(scienceSubject);
        Internal = scienceSubject;
    }

    /// <inheritdoc />
    public float DataScale
        => Internal.DataScale;

    /// <inheritdoc />
    public bool IsComplete
        => Internal.IsComplete;

    /// <inheritdoc />
    public float Science
        => Internal.Science;

    /// <inheritdoc />
    public float ScienceCap
        => Internal.ScienceCap;

    /// <inheritdoc />
    public float ScientificValue
        => Internal.ScientificValue;

    /// <inheritdoc />
    public float SubjectValue
        => Internal.SubjectValue;

    /// <inheritdoc />
    public string Title
        => Internal.Title;
}
