// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseSensor = KRPC.Client.Services.SpaceCenter.Sensor;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Sensor object.
/// </summary>
public class Sensor
{
    internal BaseSensor Internal { get; }

    internal Sensor(BaseSensor sensor)
    {
        ArgumentNullException.ThrowIfNull(sensor);
        Internal = sensor;
    }

    /// <inheritdoc />
    public bool Active
    {
        get => Internal.Active;
        set => Internal.Active = value;
    }

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public string Value
        => Internal.Value;
}
