// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseSolarPanel = KRPC.Client.Services.SpaceCenter.SolarPanel;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter SolarPanel object.
/// </summary>
public class SolarPanel
{
    internal BaseSolarPanel Internal { get; }

    internal SolarPanel(BaseSolarPanel solarPanel)
    {
        ArgumentNullException.ThrowIfNull(solarPanel);
        Internal = solarPanel;
    }

    /// <inheritdoc />
    public bool Deployable
        => Internal.Deployable;

    /// <inheritdoc />
    public bool Deployed
    {
        get => Internal.Deployed;
        set => Internal.Deployed = value;
    }

    /// <inheritdoc />
    public float EnergyFlow
        => Internal.EnergyFlow;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public SolarPanelState State
        => Internal.State;

    /// <inheritdoc />
    public float SunExposure
        => Internal.SunExposure;
}
