// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseThruster = KRPC.Client.Services.SpaceCenter.Thruster;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Thruster object.
/// </summary>
public class Thruster
{
    internal BaseThruster Internal { get; }

    internal Thruster(BaseThruster thruster)
    {
        ArgumentNullException.ThrowIfNull(thruster);
        Internal = thruster;
    }

    /// <inheritdoc />
    public Tuple<double, double, double> GimbalAngle
        => Internal.GimbalAngle;

    /// <inheritdoc />
    public bool Gimballed
        => Internal.Gimballed;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public ReferenceFrame ThrustReferenceFrame
        => new ReferenceFrame(Internal.ThrustReferenceFrame);

    /// <inheritdoc />
    public Tuple<double, double, double> GimbalPosition(ReferenceFrame referenceFrame)
        => Internal.GimbalPosition(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> InitialThrustDirection(ReferenceFrame referenceFrame)
        => Internal.InitialThrustDirection(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> InitialThrustPosition(ReferenceFrame referenceFrame)
        => Internal.InitialThrustPosition(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> ThrustDirection(ReferenceFrame referenceFrame)
        => Internal.ThrustDirection(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> ThrustPosition(ReferenceFrame referenceFrame)
        => Internal.ThrustPosition(referenceFrame.Internal);
}
