// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseVessel = KRPC.Client.Services.SpaceCenter.Vessel;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Vessel object.
/// </summary>
public class Vessel
{
    internal BaseVessel Internal { get; }

    internal Vessel(BaseVessel vessel)
    {
        ArgumentNullException.ThrowIfNull(vessel);
        Internal = vessel;
    }

    /// <inheritdoc />
    public AutoPilot AutoPilot
        => new AutoPilot(Internal.AutoPilot);

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableControlSurfaceTorque
        => Internal.AvailableControlSurfaceTorque;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableEngineTorque
        => Internal.AvailableEngineTorque;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableOtherTorque
        => Internal.AvailableOtherTorque;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableRCSForce
        => Internal.AvailableRCSForce;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableRCSTorque
        => Internal.AvailableRCSTorque;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableReactionWheelTorque
        => Internal.AvailableReactionWheelTorque;

    /// <inheritdoc />
    public float AvailableThrust
        => Internal.AvailableThrust;

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> AvailableTorque
        => Internal.AvailableTorque;

    /// <inheritdoc />
    public string Biome
        => Internal.Biome;

    /// <inheritdoc />
    public Comms Comms
        => new Comms(Internal.Comms);

    /// <inheritdoc />
    public Control Control
        => new Control(Internal.Control);

    /// <inheritdoc />
    public IList<CrewMember> Crew
        => Internal.Crew.Select(item => new CrewMember(item)).ToList();

    /// <inheritdoc />
    public int CrewCapacity
        => Internal.CrewCapacity;

    /// <inheritdoc />
    public int CrewCount
        => Internal.CrewCount;

    /// <inheritdoc />
    public float DryMass
        => Internal.DryMass;

    /// <inheritdoc />
    public IList<double> InertiaTensor
        => Internal.InertiaTensor;

    /// <inheritdoc />
    public float KerbinSeaLevelSpecificImpulse
        => Internal.KerbinSeaLevelSpecificImpulse;

    /// <inheritdoc />
    public double MET
        => Internal.MET;

    /// <inheritdoc />
    public float Mass
        => Internal.Mass;

    /// <inheritdoc />
    public float MaxThrust
        => Internal.MaxThrust;

    /// <inheritdoc />
    public float MaxVacuumThrust
        => Internal.MaxVacuumThrust;

    /// <inheritdoc />
    public Tuple<double, double, double> MomentOfInertia
        => Internal.MomentOfInertia;

    /// <inheritdoc />
    public string Name
    {
        get => Internal.Name;
        set => Internal.Name = value;
    }

    /// <inheritdoc />
    public Orbit Orbit
        => new Orbit(Internal.Orbit);

    /// <inheritdoc />
    public ReferenceFrame OrbitalReferenceFrame
        => new ReferenceFrame(Internal.OrbitalReferenceFrame);

    /// <inheritdoc />
    public Parts Parts
        => new Parts(Internal.Parts);

    /// <inheritdoc />
    public bool Recoverable
        => Internal.Recoverable;

    /// <inheritdoc />
    public ReferenceFrame ReferenceFrame
        => new ReferenceFrame(Internal.ReferenceFrame);

    /// <inheritdoc />
    public Resources Resources
        => new Resources(Internal.Resources);

    /// <inheritdoc />
    public VesselSituation Situation
        => Internal.Situation;

    /// <inheritdoc />
    public float SpecificImpulse
        => Internal.SpecificImpulse;

    /// <inheritdoc />
    public ReferenceFrame SurfaceReferenceFrame
        => new ReferenceFrame(Internal.SurfaceReferenceFrame);

    /// <inheritdoc />
    public ReferenceFrame SurfaceVelocityReferenceFrame
        => new ReferenceFrame(Internal.SurfaceVelocityReferenceFrame);

    /// <inheritdoc />
    public float Thrust
        => Internal.Thrust;

    /// <inheritdoc />
    public VesselType Type
    {
        get => Internal.Type;
        set => Internal.Type = value;
    }

    /// <inheritdoc />
    public float VacuumSpecificImpulse
        => Internal.VacuumSpecificImpulse;

    /// <inheritdoc />
    public Tuple<double, double, double> AngularVelocity(ReferenceFrame referenceFrame)
        => Internal.AngularVelocity(referenceFrame.Internal);

    /// <inheritdoc />
    public float AvailableThrustAt(double pressure)
        => Internal.AvailableThrustAt(pressure);

    /// <inheritdoc />
    public Tuple<Tuple<double, double, double>, Tuple<double, double, double>> BoundingBox(ReferenceFrame referenceFrame)
        => Internal.BoundingBox(referenceFrame.Internal);

    /// <inheritdoc />
    public Tuple<double, double, double> Direction(ReferenceFrame referenceFrame)
        => Internal.Direction(referenceFrame.Internal);

    /// <inheritdoc />
    public Flight Flight(ReferenceFrame? referenceFrame = null)
        => new Flight(Internal.Flight(referenceFrame?.Internal));

    /// <inheritdoc />
    public float MaxThrustAt(double pressure)
        => Internal.MaxThrustAt(pressure);

    /// <inheritdoc />
    public Tuple<double, double, double> Position(ReferenceFrame referenceFrame)
        => Internal.Position(referenceFrame.Internal);

    /// <inheritdoc />
    public void Recover()
        => Internal.Recover();

    /// <inheritdoc />
    public Resources ResourcesInDecoupleStage(int stage, bool cumulative = true)
        => new Resources(Internal.ResourcesInDecoupleStage(stage, cumulative));

    /// <inheritdoc />
    public Tuple<double, double, double, double> Rotation(ReferenceFrame referenceFrame)
        => Internal.Rotation(referenceFrame.Internal);

    /// <inheritdoc />
    public float SpecificImpulseAt(double pressure)
        => Internal.SpecificImpulseAt(pressure);

    /// <inheritdoc />
    public Tuple<double, double, double> Velocity(ReferenceFrame referenceFrame)
        => Internal.Velocity(referenceFrame.Internal);
}
