// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseWaypoint = KRPC.Client.Services.SpaceCenter.Waypoint;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Waypoint object.
/// </summary>
public class Waypoint
{
    internal BaseWaypoint Internal { get; }

    internal Waypoint(BaseWaypoint waypoint)
    {
        ArgumentNullException.ThrowIfNull(waypoint);
        Internal = waypoint;
    }

    /// <inheritdoc />
    public double BedrockAltitude
    {
        get => Internal.BedrockAltitude;
        set => Internal.BedrockAltitude = value;
    }

    /// <inheritdoc />
    public CelestialBody Body
    {
        get => new CelestialBody(Internal.Body);
        set => Internal.Body = value.Internal;
    }

    /// <inheritdoc />
    public bool Clustered
        => Internal.Clustered;

    /// <inheritdoc />
    public int Color
    {
        get => Internal.Color;
        set => Internal.Color = value;
    }

    /// <inheritdoc />
    public Contract Contract
        => new Contract(Internal.Contract);

    /// <inheritdoc />
    public bool Grounded
        => Internal.Grounded;

    /// <inheritdoc />
    public bool HasContract
        => Internal.HasContract;

    /// <inheritdoc />
    public string Icon
    {
        get => Internal.Icon;
        set => Internal.Icon = value;
    }

    /// <inheritdoc />
    public int Index
        => Internal.Index;

    /// <inheritdoc />
    public double Latitude
    {
        get => Internal.Latitude;
        set => Internal.Latitude = value;
    }

    /// <inheritdoc />
    public double Longitude
    {
        get => Internal.Longitude;
        set => Internal.Longitude = value;
    }

    /// <inheritdoc />
    public double MeanAltitude
    {
        get => Internal.MeanAltitude;
        set => Internal.MeanAltitude = value;
    }

    /// <inheritdoc />
    public string Name
    {
        get => Internal.Name;
        set => Internal.Name = value;
    }

    /// <inheritdoc />
    public bool NearSurface
        => Internal.NearSurface;

    /// <inheritdoc />
    public double SurfaceAltitude
    {
        get => Internal.SurfaceAltitude;
        set => Internal.SurfaceAltitude = value;
    }

    /// <inheritdoc />
    public void Remove()
        => Internal.Remove();
}
