// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KRPC.Client;
using KRPC.Client.Services.SpaceCenter;
using BaseWheel = KRPC.Client.Services.SpaceCenter.Wheel;

namespace kRPC.Client.Boost.Entities;

/// <summary>
/// Wraps a kRPC SpaceCenter Wheel object.
/// </summary>
public class Wheel
{
    internal BaseWheel Internal { get; }

    internal Wheel(BaseWheel wheel)
    {
        ArgumentNullException.ThrowIfNull(wheel);
        Internal = wheel;
    }

    /// <inheritdoc />
    public bool AutoFrictionControl
    {
        get => Internal.AutoFrictionControl;
        set => Internal.AutoFrictionControl = value;
    }

    /// <inheritdoc />
    public float Brakes
    {
        get => Internal.Brakes;
        set => Internal.Brakes = value;
    }

    /// <inheritdoc />
    public bool Broken
        => Internal.Broken;

    /// <inheritdoc />
    public float Deflection
        => Internal.Deflection;

    /// <inheritdoc />
    public bool Deployable
        => Internal.Deployable;

    /// <inheritdoc />
    public bool Deployed
    {
        get => Internal.Deployed;
        set => Internal.Deployed = value;
    }

    /// <inheritdoc />
    public float DriveLimiter
    {
        get => Internal.DriveLimiter;
        set => Internal.DriveLimiter = value;
    }

    /// <inheritdoc />
    public bool Grounded
        => Internal.Grounded;

    /// <inheritdoc />
    public bool HasBrakes
        => Internal.HasBrakes;

    /// <inheritdoc />
    public bool HasSuspension
        => Internal.HasSuspension;

    /// <inheritdoc />
    public float ManualFrictionControl
    {
        get => Internal.ManualFrictionControl;
        set => Internal.ManualFrictionControl = value;
    }

    /// <inheritdoc />
    public bool MotorEnabled
    {
        get => Internal.MotorEnabled;
        set => Internal.MotorEnabled = value;
    }

    /// <inheritdoc />
    public bool MotorInverted
    {
        get => Internal.MotorInverted;
        set => Internal.MotorInverted = value;
    }

    /// <inheritdoc />
    public float MotorOutput
        => Internal.MotorOutput;

    /// <inheritdoc />
    public MotorState MotorState
        => Internal.MotorState;

    /// <inheritdoc />
    public Part Part
        => new Part(Internal.Part);

    /// <inheritdoc />
    public bool Powered
        => Internal.Powered;

    /// <inheritdoc />
    public float Radius
        => Internal.Radius;

    /// <inheritdoc />
    public bool Repairable
        => Internal.Repairable;

    /// <inheritdoc />
    public float Slip
        => Internal.Slip;

    /// <inheritdoc />
    public WheelState State
        => Internal.State;

    /// <inheritdoc />
    public bool Steerable
        => Internal.Steerable;

    /// <inheritdoc />
    public float SteeringAngleLimit
    {
        get => Internal.SteeringAngleLimit;
        set => Internal.SteeringAngleLimit = value;
    }

    /// <inheritdoc />
    public bool SteeringEnabled
    {
        get => Internal.SteeringEnabled;
        set => Internal.SteeringEnabled = value;
    }

    /// <inheritdoc />
    public bool SteeringInverted
    {
        get => Internal.SteeringInverted;
        set => Internal.SteeringInverted = value;
    }

    /// <inheritdoc />
    public float SteeringResponseTime
    {
        get => Internal.SteeringResponseTime;
        set => Internal.SteeringResponseTime = value;
    }

    /// <inheritdoc />
    public float Stress
        => Internal.Stress;

    /// <inheritdoc />
    public float StressPercentage
        => Internal.StressPercentage;

    /// <inheritdoc />
    public float StressTolerance
        => Internal.StressTolerance;

    /// <inheritdoc />
    public float SuspensionDamperStrength
        => Internal.SuspensionDamperStrength;

    /// <inheritdoc />
    public float SuspensionSpringStrength
        => Internal.SuspensionSpringStrength;

    /// <inheritdoc />
    public float TractionControl
    {
        get => Internal.TractionControl;
        set => Internal.TractionControl = value;
    }

    /// <inheritdoc />
    public bool TractionControlEnabled
    {
        get => Internal.TractionControlEnabled;
        set => Internal.TractionControlEnabled = value;
    }
}
