using kRPC.Client.Boost.Connection;
using kRPC.Client.Boost.Services;
using kRPC.Client.Boost.Attributes;
using System.Threading.Tasks;

namespace kRPC.Client.Boost.Services.SpaceCenter;

/// <summary>
/// A solar panel. Obtained by calling <see cref="M:SpaceCenter.Part.GetSolarPanel" />.
/// </summary>
public class SolarPanel : RemoteObject
{
    /// <summary>
    /// Construct an instance of this remote object. Should not be called directly. This interface is intended for internal decoding.
    /// </summary>
    public SolarPanel(ConnectionMultiplexer connection, ulong id) : base(connection, id)
    {
    }

    /// <summary>
    /// Gets whether the solar panel is deployable.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_Deployable")]
    public bool GetDeployable()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<bool>("SpaceCenter", "SolarPanel_get_Deployable", args);
    }

    /// <summary>
    /// Gets whether the solar panel is deployable.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_Deployable")]
    public async Task<bool> GetDeployableAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<bool>("SpaceCenter", "SolarPanel_get_Deployable", args);
    }

    /// <summary>
    /// Gets whether the solar panel is extended.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_Deployed")]
    public bool GetDeployed()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<bool>("SpaceCenter", "SolarPanel_get_Deployed", args);
    }

    /// <summary>
    /// Gets whether the solar panel is extended.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_Deployed")]
    public async Task<bool> GetDeployedAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<bool>("SpaceCenter", "SolarPanel_get_Deployed", args);
    }

    /// <summary>
    /// Sets whether the solar panel is extended.
    /// </summary>
    /// <param name="value">The value to set.</param>
    [Rpc("SpaceCenter", "SolarPanel_set_Deployed")]
    public void SetDeployed(bool value)
    {
        var args = new object[]
        {
            this,
            value
        };
        Connection.Invoke("SpaceCenter", "SolarPanel_set_Deployed", args);
    }

    /// <summary>
    /// Sets whether the solar panel is extended.
    /// Executes asynchronously.
    /// </summary>
    /// <param name="value">The value to set.</param>
    [Rpc("SpaceCenter", "SolarPanel_set_Deployed")]
    public async Task SetDeployedAsync(bool value)
    {
        var args = new object[]
        {
            this,
            value
        };
        await Connection.InvokeAsync("SpaceCenter", "SolarPanel_set_Deployed", args);
    }

    /// <summary>
    /// Gets the current amount of energy being generated by the solar panel, in
    /// units of charge per second.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_EnergyFlow")]
    public float GetEnergyFlow()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<float>("SpaceCenter", "SolarPanel_get_EnergyFlow", args);
    }

    /// <summary>
    /// Gets the current amount of energy being generated by the solar panel, in
    /// units of charge per second.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_EnergyFlow")]
    public async Task<float> GetEnergyFlowAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<float>("SpaceCenter", "SolarPanel_get_EnergyFlow", args);
    }

    /// <summary>
    /// Gets the part object for this solar panel.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_Part")]
    public Part GetPart()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<Part>("SpaceCenter", "SolarPanel_get_Part", args);
    }

    /// <summary>
    /// Gets the part object for this solar panel.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_Part")]
    public async Task<Part> GetPartAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<Part>("SpaceCenter", "SolarPanel_get_Part", args);
    }

    /// <summary>
    /// Gets the current state of the solar panel.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_State")]
    public SolarPanelState GetState()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<SolarPanelState>("SpaceCenter", "SolarPanel_get_State", args);
    }

    /// <summary>
    /// Gets the current state of the solar panel.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_State")]
    public async Task<SolarPanelState> GetStateAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<SolarPanelState>("SpaceCenter", "SolarPanel_get_State", args);
    }

    /// <summary>
    /// Gets the current amount of sunlight that is incident on the solar panel,
    /// as a percentage. A value between 0 and 1.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_SunExposure")]
    public float GetSunExposure()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<float>("SpaceCenter", "SolarPanel_get_SunExposure", args);
    }

    /// <summary>
    /// Gets the current amount of sunlight that is incident on the solar panel,
    /// as a percentage. A value between 0 and 1.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "SolarPanel_get_SunExposure")]
    public async Task<float> GetSunExposureAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<float>("SpaceCenter", "SolarPanel_get_SunExposure", args);
    }
}
