using kRPC.Client.Boost.Connection;
using kRPC.Client.Boost.Services;
using kRPC.Client.Boost.Attributes;

namespace kRPC.Client.Boost.Services.SpaceCenter;

/// <summary>
/// A solar panel. Obtained by calling <see cref="M:SpaceCenter.Part.SolarPanel" />.
/// </summary>
public class SolarPanel : RemoteObject
{
    /// <summary>
    /// Construct an instance of this remote object. Should not be called directly. This interface is intended for internal decoding.
    /// </summary>
    public SolarPanel (ConnectionMultiplexer connection, ulong id) : base (connection, id)
    {
    }

    /// <summary>
    /// Whether the solar panel is deployable.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "SolarPanel_get_Deployable")]
    public bool Deployable {
        get {
            var args = new object[] {
                this
            };
            return Connection.Invoke<bool> ("SpaceCenter", "SolarPanel_get_Deployable", args);
        }
    }

    /// <summary>
    /// Whether the solar panel is extended.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "SolarPanel_get_Deployed")]
    public bool Deployed {
        get {
            var args = new object[] {
                this
            };
            return Connection.Invoke<bool> ("SpaceCenter", "SolarPanel_get_Deployed", args);
        }
        set {
            var args = new object[] {
                this,
                value
            };
            Connection.Invoke ("SpaceCenter", "SolarPanel_set_Deployed", args);
        }
    }

    /// <summary>
    /// The current amount of energy being generated by the solar panel, in
    /// units of charge per second.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "SolarPanel_get_EnergyFlow")]
    public float EnergyFlow {
        get {
            var args = new object[] {
                this
            };
            return Connection.Invoke<float> ("SpaceCenter", "SolarPanel_get_EnergyFlow", args);
        }
    }

    /// <summary>
    /// The part object for this solar panel.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "SolarPanel_get_Part")]
    public Part Part {
        get {
            var args = new object[] {
                this
            };
            return Connection.Invoke<Part> ("SpaceCenter", "SolarPanel_get_Part", args);
        }
    }

    /// <summary>
    /// The current state of the solar panel.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "SolarPanel_get_State")]
    public SolarPanelState State {
        get {
            var args = new object[] {
                this
            };
            return Connection.Invoke<SolarPanelState> ("SpaceCenter", "SolarPanel_get_State", args);
        }
    }

    /// <summary>
    /// The current amount of sunlight that is incident on the solar panel,
    /// as a percentage. A value between 0 and 1.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "SolarPanel_get_SunExposure")]
    public float SunExposure {
        get {
            var args = new object[] {
                this
            };
            return Connection.Invoke<float> ("SpaceCenter", "SolarPanel_get_SunExposure", args);
        }
    }
}
