using kRPC.Client.Boost.Connection;
using kRPC.Client.Boost.Services;
using System;
using kRPC.Client.Boost.Attributes;
using MathNet.Spatial.Euclidean;
using System.Threading.Tasks;

namespace kRPC.Client.Boost.Services.SpaceCenter;

/// <summary>
/// The component of an <see cref="T:SpaceCenter.Engine" /> or <see cref="T:SpaceCenter.RCS" /> part that generates thrust.
/// Can be obtained by calling <see cref="M:SpaceCenter.Engine.GetThrusters" /> or <see cref="M:SpaceCenter.RCS.GetThrusters" />.
/// </summary>
/// <remarks>
/// Engines can consist of multiple thrusters.
/// For example, the S3 KS-25x4 "Mammoth" has four rocket nozzels, and so consists of
/// four thrusters.
/// </remarks>
public class Thruster : RemoteObject
{
    /// <summary>
    /// Construct an instance of this remote object. Should not be called directly. This interface is intended for internal decoding.
    /// </summary>
    public Thruster(ConnectionMultiplexer connection, ulong id) : base(connection, id)
    {
    }

    /// <summary>
    /// Position around which the gimbal pivots.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    [Rpc("SpaceCenter", "Thruster_GimbalPosition")]
    public Vector3D GimbalPosition(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return Connection.Invoke<Vector3D>("SpaceCenter", "Thruster_GimbalPosition", args);
    }

    /// <summary>
    /// Position around which the gimbal pivots.
    /// Executes asynchronously.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    [Rpc("SpaceCenter", "Thruster_GimbalPosition")]
    public async Task<Vector3D> GimbalPositionAsync(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return await Connection.InvokeAsync<Vector3D>("SpaceCenter", "Thruster_GimbalPosition", args);
    }

    /// <summary>
    /// The direction of the force generated by the thruster, when the engine is in its
    /// initial position (no gimballing), in the given reference frame.
    /// This is opposite to the direction in which the thruster expels propellant.
    /// </summary>
    /// <returns>The direction as a unit vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// direction is in.</param>
    [Rpc("SpaceCenter", "Thruster_InitialThrustDirection")]
    public Vector3D InitialThrustDirection(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return Connection.Invoke<Vector3D>("SpaceCenter", "Thruster_InitialThrustDirection", args);
    }

    /// <summary>
    /// The direction of the force generated by the thruster, when the engine is in its
    /// initial position (no gimballing), in the given reference frame.
    /// This is opposite to the direction in which the thruster expels propellant.
    /// Executes asynchronously.
    /// </summary>
    /// <returns>The direction as a unit vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// direction is in.</param>
    [Rpc("SpaceCenter", "Thruster_InitialThrustDirection")]
    public async Task<Vector3D> InitialThrustDirectionAsync(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return await Connection.InvokeAsync<Vector3D>("SpaceCenter", "Thruster_InitialThrustDirection", args);
    }

    /// <summary>
    /// The position at which the thruster generates thrust, when the engine is in its
    /// initial position (no gimballing), in the given reference frame.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    /// <remarks>
    /// This position can move when the gimbal rotates. This is because the thrust position and
    /// gimbal position are not necessarily the same.
    /// </remarks>
    [Rpc("SpaceCenter", "Thruster_InitialThrustPosition")]
    public Vector3D InitialThrustPosition(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return Connection.Invoke<Vector3D>("SpaceCenter", "Thruster_InitialThrustPosition", args);
    }

    /// <summary>
    /// The position at which the thruster generates thrust, when the engine is in its
    /// initial position (no gimballing), in the given reference frame.
    /// Executes asynchronously.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    /// <remarks>
    /// This position can move when the gimbal rotates. This is because the thrust position and
    /// gimbal position are not necessarily the same.
    /// </remarks>
    [Rpc("SpaceCenter", "Thruster_InitialThrustPosition")]
    public async Task<Vector3D> InitialThrustPositionAsync(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return await Connection.InvokeAsync<Vector3D>("SpaceCenter", "Thruster_InitialThrustPosition", args);
    }

    /// <summary>
    /// The direction of the force generated by the thruster, in the given reference frame.
    /// This is opposite to the direction in which the thruster expels propellant.
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// </summary>
    /// <returns>The direction as a unit vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// direction is in.</param>
    [Rpc("SpaceCenter", "Thruster_ThrustDirection")]
    public Vector3D ThrustDirection(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return Connection.Invoke<Vector3D>("SpaceCenter", "Thruster_ThrustDirection", args);
    }

    /// <summary>
    /// The direction of the force generated by the thruster, in the given reference frame.
    /// This is opposite to the direction in which the thruster expels propellant.
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// Executes asynchronously.
    /// </summary>
    /// <returns>The direction as a unit vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// direction is in.</param>
    [Rpc("SpaceCenter", "Thruster_ThrustDirection")]
    public async Task<Vector3D> ThrustDirectionAsync(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return await Connection.InvokeAsync<Vector3D>("SpaceCenter", "Thruster_ThrustDirection", args);
    }

    /// <summary>
    /// The position at which the thruster generates thrust, in the given reference frame.
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    [Rpc("SpaceCenter", "Thruster_ThrustPosition")]
    public Vector3D ThrustPosition(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return Connection.Invoke<Vector3D>("SpaceCenter", "Thruster_ThrustPosition", args);
    }

    /// <summary>
    /// The position at which the thruster generates thrust, in the given reference frame.
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// Executes asynchronously.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    [Rpc("SpaceCenter", "Thruster_ThrustPosition")]
    public async Task<Vector3D> ThrustPositionAsync(ReferenceFrame referenceFrame)
    {
        var args = new object[]
        {
            this,
            referenceFrame
        };
        return await Connection.InvokeAsync<Vector3D>("SpaceCenter", "Thruster_ThrustPosition", args);
    }

    /// <summary>
    /// Gets the current gimbal angle in the pitch, roll and yaw axes, in degrees.
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_GimbalAngle")]
    public Tuple<double,double,double> GetGimbalAngle()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<Tuple<double,double,double>>("SpaceCenter", "Thruster_get_GimbalAngle", args);
    }

    /// <summary>
    /// Gets the current gimbal angle in the pitch, roll and yaw axes, in degrees.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_GimbalAngle")]
    public async Task<Tuple<double,double,double>> GetGimbalAngleAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<Tuple<double,double,double>>("SpaceCenter", "Thruster_get_GimbalAngle", args);
    }

    /// <summary>
    /// Gets whether the thruster is gimballed.
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_Gimballed")]
    public bool GetGimballed()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<bool>("SpaceCenter", "Thruster_get_Gimballed", args);
    }

    /// <summary>
    /// Gets whether the thruster is gimballed.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_Gimballed")]
    public async Task<bool> GetGimballedAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<bool>("SpaceCenter", "Thruster_get_Gimballed", args);
    }

    /// <summary>
    /// Gets the <see cref="T:SpaceCenter.Part" /> that contains this thruster.
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_Part")]
    public Part GetPart()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<Part>("SpaceCenter", "Thruster_get_Part", args);
    }

    /// <summary>
    /// Gets the <see cref="T:SpaceCenter.Part" /> that contains this thruster.
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_Part")]
    public async Task<Part> GetPartAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<Part>("SpaceCenter", "Thruster_get_Part", args);
    }

    /// <summary>
    /// Gets a reference frame that is fixed relative to the thruster and orientated with
    /// its thrust direction (<see cref="M:SpaceCenter.Thruster.ThrustDirection" />).
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// <list type="bullet"><item><description>
    /// The origin is at the position of thrust for this thruster
    /// (<see cref="M:SpaceCenter.Thruster.ThrustPosition" />).</description></item><item><description>
    /// The axes rotate with the thrust direction.
    /// This is the direction in which the thruster expels propellant, including any gimballing.
    /// </description></item><item><description>The y-axis points along the thrust direction.</description></item><item><description>The x-axis and z-axis are perpendicular to the thrust direction.
    /// </description></item></list>
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_ThrustReferenceFrame")]
    public ReferenceFrame GetThrustReferenceFrame()
    {
        var args = new object[]
        {
            this
        };
        return Connection.Invoke<ReferenceFrame>("SpaceCenter", "Thruster_get_ThrustReferenceFrame", args);
    }

    /// <summary>
    /// Gets a reference frame that is fixed relative to the thruster and orientated with
    /// its thrust direction (<see cref="M:SpaceCenter.Thruster.ThrustDirection" />).
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// <list type="bullet"><item><description>
    /// The origin is at the position of thrust for this thruster
    /// (<see cref="M:SpaceCenter.Thruster.ThrustPosition" />).</description></item><item><description>
    /// The axes rotate with the thrust direction.
    /// This is the direction in which the thruster expels propellant, including any gimballing.
    /// </description></item><item><description>The y-axis points along the thrust direction.</description></item><item><description>The x-axis and z-axis are perpendicular to the thrust direction.
    /// </description></item></list>
    /// Executes asynchronously.
    /// </summary>
    [Rpc("SpaceCenter", "Thruster_get_ThrustReferenceFrame")]
    public async Task<ReferenceFrame> GetThrustReferenceFrameAsync()
    {
        var args = new object[]
        {
            this
        };
        return await Connection.InvokeAsync<ReferenceFrame>("SpaceCenter", "Thruster_get_ThrustReferenceFrame", args);
    }
}
