using kRPC.Client.Boost.Connection;
using kRPC.Client.Boost.Services;
using Google.Protobuf;
using systemAlias = System;
using kRPC.Client.Boost.Attributes;

namespace kRPC.Client.Boost.Services.SpaceCenter;

/// <summary>
/// The component of an <see cref="T:SpaceCenter.Engine" /> or <see cref="T:SpaceCenter.RCS" /> part that generates thrust.
/// Can obtained by calling <see cref="M:SpaceCenter.Engine.Thrusters" /> or <see cref="M:SpaceCenter.RCS.Thrusters" />.
/// </summary>
/// <remarks>
/// Engines can consist of multiple thrusters.
/// For example, the S3 KS-25x4 "Mammoth" has four rocket nozzels, and so consists of
/// four thrusters.
/// </remarks>
public class Thruster : RemoteObject
{
    /// <summary>
    /// Construct an instance of this remote object. Should not be called directly. This interface is intended for internal decoding.
    /// </summary>
    public Thruster (ConnectionMultiplexer connection, ulong id) : base (connection, id)
    {
    }

    /// <summary>
    /// Position around which the gimbal pivots.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    [RpcAttribute ("SpaceCenter", "Thruster_GimbalPosition")]
    public systemAlias::Tuple<double,double,double> GimbalPosition (global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame referenceFrame)
    {
        var _args = new ByteString[] {
            global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster)),
            global::KRPC.Client.Encoder.Encode (referenceFrame, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame))
        };
        ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_GimbalPosition", _args);
        return (systemAlias::Tuple<double,double,double>)global::KRPC.Client.Encoder.Decode (_data, typeof(systemAlias::Tuple<double,double,double>), connection);
    }

    /// <summary>
    /// The direction of the force generated by the thruster, when the engine is in its
    /// initial position (no gimballing), in the given reference frame.
    /// This is opposite to the direction in which the thruster expels propellant.
    /// </summary>
    /// <returns>The direction as a unit vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// direction is in.</param>
    [RpcAttribute ("SpaceCenter", "Thruster_InitialThrustDirection")]
    public systemAlias::Tuple<double,double,double> InitialThrustDirection (global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame referenceFrame)
    {
        var _args = new ByteString[] {
            global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster)),
            global::KRPC.Client.Encoder.Encode (referenceFrame, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame))
        };
        ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_InitialThrustDirection", _args);
        return (systemAlias::Tuple<double,double,double>)global::KRPC.Client.Encoder.Decode (_data, typeof(systemAlias::Tuple<double,double,double>), connection);
    }

    /// <summary>
    /// The position at which the thruster generates thrust, when the engine is in its
    /// initial position (no gimballing), in the given reference frame.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    /// <remarks>
    /// This position can move when the gimbal rotates. This is because the thrust position and
    /// gimbal position are not necessarily the same.
    /// </remarks>
    [RpcAttribute ("SpaceCenter", "Thruster_InitialThrustPosition")]
    public systemAlias::Tuple<double,double,double> InitialThrustPosition (global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame referenceFrame)
    {
        var _args = new ByteString[] {
            global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster)),
            global::KRPC.Client.Encoder.Encode (referenceFrame, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame))
        };
        ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_InitialThrustPosition", _args);
        return (systemAlias::Tuple<double,double,double>)global::KRPC.Client.Encoder.Decode (_data, typeof(systemAlias::Tuple<double,double,double>), connection);
    }

    /// <summary>
    /// The direction of the force generated by the thruster, in the given reference frame.
    /// This is opposite to the direction in which the thruster expels propellant.
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// </summary>
    /// <returns>The direction as a unit vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// direction is in.</param>
    [RpcAttribute ("SpaceCenter", "Thruster_ThrustDirection")]
    public systemAlias::Tuple<double,double,double> ThrustDirection (global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame referenceFrame)
    {
        var _args = new ByteString[] {
            global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster)),
            global::KRPC.Client.Encoder.Encode (referenceFrame, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame))
        };
        ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_ThrustDirection", _args);
        return (systemAlias::Tuple<double,double,double>)global::KRPC.Client.Encoder.Decode (_data, typeof(systemAlias::Tuple<double,double,double>), connection);
    }

    /// <summary>
    /// The position at which the thruster generates thrust, in the given reference frame.
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// </summary>
    /// <returns>The position as a vector.</returns>
    /// <param name="referenceFrame">The reference frame that the returned
    /// position vector is in.</param>
    [RpcAttribute ("SpaceCenter", "Thruster_ThrustPosition")]
    public systemAlias::Tuple<double,double,double> ThrustPosition (global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame referenceFrame)
    {
        var _args = new ByteString[] {
            global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster)),
            global::KRPC.Client.Encoder.Encode (referenceFrame, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame))
        };
        ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_ThrustPosition", _args);
        return (systemAlias::Tuple<double,double,double>)global::KRPC.Client.Encoder.Decode (_data, typeof(systemAlias::Tuple<double,double,double>), connection);
    }

    /// <summary>
    /// The current gimbal angle in the pitch, roll and yaw axes, in degrees.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "Thruster_get_GimbalAngle")]
    public systemAlias::Tuple<double,double,double> GimbalAngle {
        get {
            var _args = new ByteString[] {
                global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster))
            };
            ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_get_GimbalAngle", _args);
            return (systemAlias::Tuple<double,double,double>)global::KRPC.Client.Encoder.Decode (_data, typeof(systemAlias::Tuple<double,double,double>), connection);
        }
    }

    /// <summary>
    /// Whether the thruster is gimballed.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "Thruster_get_Gimballed")]
    public bool Gimballed {
        get {
            var _args = new ByteString[] {
                global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster))
            };
            ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_get_Gimballed", _args);
            return (bool)global::KRPC.Client.Encoder.Decode (_data, typeof(bool), connection);
        }
    }

    /// <summary>
    /// The <see cref="T:SpaceCenter.Part" /> that contains this thruster.
    /// </summary>
    [RpcAttribute ("SpaceCenter", "Thruster_get_Part")]
    public global::kRPC.Client.Boost.Services.SpaceCenter.Part Part {
        get {
            var _args = new ByteString[] {
                global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster))
            };
            ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_get_Part", _args);
            return (global::kRPC.Client.Boost.Services.SpaceCenter.Part)global::KRPC.Client.Encoder.Decode (_data, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Part), connection);
        }
    }

    /// <summary>
    /// A reference frame that is fixed relative to the thruster and orientated with
    /// its thrust direction (<see cref="M:SpaceCenter.Thruster.ThrustDirection" />).
    /// For gimballed engines, this takes into account the current rotation of the gimbal.
    /// <list type="bullet"><item><description>
    /// The origin is at the position of thrust for this thruster
    /// (<see cref="M:SpaceCenter.Thruster.ThrustPosition" />).</description></item><item><description>
    /// The axes rotate with the thrust direction.
    /// This is the direction in which the thruster expels propellant, including any gimballing.
    /// </description></item><item><description>The y-axis points along the thrust direction.</description></item><item><description>The x-axis and z-axis are perpendicular to the thrust direction.
    /// </description></item></list></summary>
    [RpcAttribute ("SpaceCenter", "Thruster_get_ThrustReferenceFrame")]
    public global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame ThrustReferenceFrame {
        get {
            var _args = new ByteString[] {
                global::KRPC.Client.Encoder.Encode (this, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.Thruster))
            };
            ByteString _data = connection.Invoke ("SpaceCenter", "Thruster_get_ThrustReferenceFrame", _args);
            return (global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame)global::KRPC.Client.Encoder.Decode (_data, typeof(global::kRPC.Client.Boost.Services.SpaceCenter.ReferenceFrame), connection);
        }
    }
}
